import { StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import { portalPalette } from '../portal-theme';

export const styles = StyleSheet.create({
  billingClarity: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderColor: 'rgba(35, 213, 255, 0.18)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  billingClarityText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
  },
  subscriptionContent: {
    gap: 12,
  },
  cancelSubscriptionButton: {
    alignItems: 'center',
    alignSelf: 'flex-end',
    borderColor: portalPalette.danger,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  cancelSubscriptionText: {
    color: portalPalette.danger,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  currentPlanCard: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    gap: AppTheme.spacing.md,
    padding: AppTheme.spacing.lg,
  },
  currentPlanHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  currentPlanIdentity: {
    flex: 1,
    flexBasis: 280,
    gap: 4,
    minWidth: 0,
  },
  eyebrow: {
    color: portalPalette.accent,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  currentPlanName: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 34,
  },
  currentPlanDescription: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 620,
  },
  currentMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  planFact: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 170,
    gap: 4,
    minHeight: 82,
    minWidth: 0,
    padding: 12,
  },
  planFactLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
  },
  planFactValue: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 23,
  },
  usageBlock: {
    gap: 8,
  },
  usageHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  usageLabel: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  usageValue: {
    color: portalPalette.accent,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  usageTrack: {
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.pill,
    height: 10,
    overflow: 'hidden',
  },
  usageFill: {
    backgroundColor: portalPalette.accent,
    borderRadius: AppTheme.radius.pill,
    height: 10,
  },
  usageHint: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  planGridWrapper: {
    marginHorizontal: -4,
    overflow: 'hidden',
  },
  planGrid: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    gap: 12,
    minWidth: 0,
    overflow: 'auto',
    paddingBottom: 4,
    scrollBehavior: 'smooth' as any,
    WebkitOverflowScrolling: 'touch' as any,
  },
  planCard: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    flex: 1,
    flexBasis: 260,
    gap: 12,
    minWidth: 240,
    padding: AppTheme.spacing.md,
  },
  planCardSelected: {
    backgroundColor: portalPalette.accentSoft,
    borderColor: portalPalette.accent,
  },
  planCardActive: {
    borderColor: 'rgba(82, 242, 167, 0.45)',
  },
  planCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  planCardTitleWrap: {
    flex: 1,
    flexBasis: 150,
    gap: 3,
    minWidth: 0,
  },
  planName: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 20,
    fontWeight: '900',
  },
  planDescription: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  priceRow: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  planPrice: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
  },
  pricePeriod: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
  },
  unitPrice: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  benefitList: {
    flex: 1,
    gap: 7,
  },
  benefitRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
  },
  benefitText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
  },
  compareButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  compareButtonText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  compareButtonTextSelected: {
    color: '#FFFFFF',
  },
  currentPlanAction: {
    alignItems: 'center',
    backgroundColor: portalPalette.successSoft,
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  currentPlanActionText: {
    color: portalPalette.success,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  planSkeleton: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    flex: 1,
    flexBasis: 260,
    gap: 13,
    minHeight: 230,
    minWidth: 240,
    padding: AppTheme.spacing.md,
  },
  comparisonFlow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  comparisonFlowCompact: {
    flexDirection: 'column',
  },
  comparisonPlan: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 250,
    gap: 5,
    minWidth: 0,
    padding: AppTheme.spacing.md,
  },
  comparisonPlanFeatured: {
    backgroundColor: portalPalette.accentSoft,
    borderColor: portalPalette.accent,
  },
  comparisonPlanCompact: {
    flexBasis: 'auto',
    width: '100%',
  },
  comparisonArrow: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: portalPalette.accentSoft,
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  comparisonLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  comparisonName: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 21,
    fontWeight: '900',
  },
  comparisonMeta: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  changeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  changeFact: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 210,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
    padding: 12,
  },
  changeFactIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderRadius: 10,
    flexShrink: 0,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  changeFactCopy: {
    flex: 1,
    minWidth: 0,
  },
  changeFactLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
  },
  changeFactValue: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 18,
  },
  newBenefits: {
    backgroundColor: portalPalette.successSoft,
    borderColor: 'rgba(82, 242, 167, 0.22)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    gap: 8,
    padding: AppTheme.spacing.md,
  },
  newBenefitsTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  ruleNotice: {
    alignItems: 'flex-start',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: AppTheme.spacing.md,
  },
  ruleNoticeAllowed: {
    backgroundColor: portalPalette.successSoft,
    borderColor: 'rgba(82, 242, 167, 0.24)',
  },
  ruleNoticeBlocked: {
    backgroundColor: portalPalette.warningSoft,
    borderColor: 'rgba(255, 209, 102, 0.28)',
  },
  ruleNoticeCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  ruleNoticeTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  ruleNoticeText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  restrictionText: {
    color: portalPalette.warning,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  nextStepText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 2,
  },
  actionFeedback: {
    alignItems: 'flex-start',
    backgroundColor: portalPalette.infoSoft,
    borderColor: 'rgba(35, 213, 255, 0.24)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: AppTheme.spacing.md,
    padding: AppTheme.spacing.md,
  },
  plansErrorState: {
    alignItems: 'center',
    gap: 12,
  },
  retryButton: {
    alignItems: 'center',
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 18,
  },
  retryButtonText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  actionFeedbackText: {
    color: portalPalette.muted,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  previewActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'flex-end',
  },
  previewActionsCompact: {
    flexDirection: 'column',
  },
  fullWidthButton: {
    width: '100%',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 16,
  },
  secondaryButtonText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  continueButton: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 150,
    paddingHorizontal: 16,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.58,
  },
  comparisonEmpty: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: AppTheme.spacing.md,
  },
  comparisonEmptyIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  comparisonEmptyCopy: {
    flex: 1,
    flexBasis: 240,
    gap: 3,
    minWidth: 0,
  },
  comparisonEmptyTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  comparisonEmptyText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
});
