import type { CommercialPlan } from '@/src/types/app';

export const FALLBACK_COMMERCIAL_PLANS: CommercialPlan[] = [
  {
    id: 'starter-2',
    name: '2 combis',
    units: 2,
    price: 149,
    pricePerVehicle: 74.5,
    strategy: 'Entrada',
    badge: 'Arranque rapido',
    accent: 'info',
    subtitle: 'Ideal para pilotos y patios pequenos',
    trialDays: 7,
    trialEligible: true,
    includesRadioModule: false,
    radioAddonEligible: true,
    radioAddonPrice: 20,
  },
  {
    id: 'value-4',
    name: '4 combis',
    units: 4,
    price: 209,
    pricePerVehicle: 52.3,
    strategy: 'Mejor valor',
    badge: 'Mas vendido',
    accent: 'success',
    subtitle: 'El punto de entrada mas balanceado',
    trialDays: 7,
    trialEligible: true,
    includesRadioModule: false,
    radioAddonEligible: true,
    radioAddonPrice: 20,
  },
  {
    id: 'control-6',
    name: '6 combis',
    units: 6,
    price: 299,
    pricePerVehicle: 49.8,
    strategy: 'Ajustado',
    badge: 'Operacion estable',
    accent: 'warning',
    subtitle: 'Pensado para crecimiento con control operativo',
    trialDays: 7,
    trialEligible: true,
    includesRadioModule: false,
    radioAddonEligible: true,
    radioAddonPrice: 20,
  },
  {
    id: 'premium-8',
    name: '8 combis',
    units: 8,
    price: 449,
    pricePerVehicle: 56.1,
    strategy: 'Premium',
    badge: 'Cobertura total',
    accent: 'danger',
    subtitle: 'Mayor cobertura, supervisores y evidencia',
    trialDays: 7,
    trialEligible: true,
    includesRadioModule: true,
    radioAddonEligible: false,
    radioAddonPrice: 0,
  },
  {
    id: 'enterprise-12',
    name: '12 combis',
    units: 12,
    price: 749,
    pricePerVehicle: 62.4,
    strategy: 'Empresas',
    badge: 'Escala multi patio',
    accent: 'info',
    subtitle: 'Multi patio, onboarding y despliegue empresarial',
    trialDays: 7,
    trialEligible: true,
    includesRadioModule: true,
    radioAddonEligible: false,
    radioAddonPrice: 0,
  },
];

export const COMMERCIAL_FEATURES = [
  {
    title: 'Mapa con seguimiento real',
    body: 'Sigue cada combi, cambia de unidad activa y revisa rutas, GPS y estado en segundos.',
    icon: 'map-marker-radius',
  },
  {
    title: 'Control documental',
    body: 'Licencias, seguros y verificaciones con alertas visibles antes de que caduquen.',
    icon: 'file-document-outline',
  },
  {
    title: 'Chat operativo',
    body: 'Conductores, supervisores y centro de control coordinados desde la misma app.',
    icon: 'message-text-outline',
  },
  {
    title: 'Radio con voz',
    body: 'Canal general y punto a punto con notas de voz para despachar mas rapido.',
    icon: 'radio-handheld',
  },
  {
    title: 'Bitacora y rendimiento',
    body: 'Tiempo de recorrido, vueltas por fecha y evidencia para medir puntualidad.',
    icon: 'chart-timeline-variant',
  },
];

export const COMMERCIAL_FAQS = [
  {
    question: 'El precio es por mes?',
    answer: 'La landing presenta los paquetes como mensualidad comercial por numero de combis activas.',
  },
  {
    question: 'Puedo arrancar con pocas unidades?',
    answer: 'Si. El plan de 2 combis es la puerta de entrada para operadores pequenos o pilotos.',
  },
  {
    question: 'La app sirve para supervisores y administracion?',
    answer: 'Si. La plataforma centraliza choferes, incidencias, documentos, seguimiento y control.',
  },
  {
    question: 'El pago queda automatizado?',
    answer: 'Si configuras Mercado Pago, el checkout abre pago real. Mientras tanto, SPEI y transferencia mantienen referencia comercial.',
  },
];
