import { StyleSheet } from 'react-native';
import { AppTheme } from '@/constants/theme';
import { Typography } from '@/constants/theme';
import { portalPalette } from '../portal-theme';
import { OPERATIONS_DETAIL_WIDTH, OPERATIONS_UNIT_SELECTOR_WIDTH } from './dashboard.constants';

export const styles = StyleSheet.create({
  disabledButton: {
    opacity: 0.55,
  },
  actionButton: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 8,
    minHeight: 44,
    paddingHorizontal: 14,
  },
  actionText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  alertRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  compactRow: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    gap: 3,
    padding: 10,
  },
  compactTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  assignedDriversPanel: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  detailGrid: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minWidth: 0,
  },
  detailPanelCol: {
    flex: 0.8,
    flexBasis: 360,
    minWidth: 0,
  },
  detailHistoryCol: {
    flex: 1.8,
    flexBasis: 640,
    minWidth: 0,
  },
  disabledAction: {
    opacity: 0.55,
  },
  driverAvatar: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderColor: portalPalette.info,
    borderRadius: 20,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  driverAvatarText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  driverName: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '900',
  },
  driverOption: {
    alignItems: 'center',
    backgroundColor: portalPalette.surface,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    minHeight: 38,
    paddingHorizontal: 10,
  },
  driverProfile: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderTopColor: 'rgba(148,163,184,.12)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 2,
    paddingVertical: 8,
    boxShadow: 'none' as any,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out' as any,
  },
  driverRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  driverRowText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
    minWidth: 0,
  },
  driverSelector: {
    gap: 6,
  },
  fact: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    flex: 1,
    flexBasis: 108,
    gap: 1,
    minWidth: 0,
    paddingHorizontal: 2,
    paddingVertical: 3,
    boxShadow: 'none' as any,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out, opacity 180ms ease-in-out' as any,
  },
  factLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
  },
  factValue: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 18,
  },
  filterChip: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    minHeight: 34,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  filterChipActive: {
    backgroundColor: portalPalette.infoSoft,
    borderColor: portalPalette.info,
  },
  filterChipText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  filterInput: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    color: portalPalette.text,
    flex: 1,
    flexBasis: 180,
    fontFamily: Typography.body,
    minHeight: 38,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  filters: {
    gap: 8,
  },
  filterSeparator: {
    alignSelf: 'center',
    backgroundColor: portalPalette.line,
    height: 20,
    width: 1,
  },
  filterToggle: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    minHeight: 30,
  },
  filterToggleText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
  },
  flex: {
    flex: 1,
    minWidth: 0,
  },
  formRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minWidth: 0,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.surface,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  inlineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  historyCard: {
    backgroundColor: 'transparent',
    borderColor: portalPalette.line,
    borderBottomWidth: 1,
    gap: 2,
    minWidth: 0,
    paddingHorizontal: 4,
    paddingVertical: 9,
    width: '100%',
  },
  historyCardActive: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.accent,
  },
  historyList: {
    gap: 0,
    minWidth: 0,
  },
  historyMeta: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  historyTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  loadingText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 14,
  },
  mapFallback: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    justifyContent: 'center',
    padding: 18,
  },
  mapStage: {
    flex: 1,
    minWidth: 0,
    position: 'relative',
  },
  mapSurface: {
    backgroundColor: '#080f1c',
    borderColor: 'rgba(148,163,184,.16)',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: AppTheme.spacing.xxl * 6,
    overflow: 'hidden',
    position: 'relative',
    boxShadow: '0 22px 52px rgba(0,0,0,.34)' as any,
  },
  mapHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    left: 12,
    minHeight: 40,
    paddingHorizontal: 12,
    paddingVertical: 4,
    position: 'absolute',
    right: 12,
    top: 12,
    zIndex: 25,
    backgroundColor: 'rgba(8,15,28,.88)',
    borderColor: 'rgba(148,163,184,.18)',
    borderRadius: 12,
    borderWidth: 1,
    boxShadow: '0 12px 30px rgba(0,0,0,.38)' as any,
    backdropFilter: 'blur(14px)' as any,
  },
  controlHover: { backgroundColor: 'rgba(255,255,255,.09)', borderColor: portalPalette.lineStrong, boxShadow: '0 8px 20px rgba(0,0,0,.18)' as any },
  controlPressed: { opacity: 0.76, transform: [{ scale: 0.98 }] },
  operationsFilter: {
    alignItems: 'center', backgroundColor: 'rgba(8, 16, 32, 0.42)', borderColor: 'transparent', borderRadius: 18,
    borderWidth: 1, flexDirection: 'row', gap: 6, minHeight: 28, paddingHorizontal: 8,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out, box-shadow 180ms ease-in-out, transform 180ms ease-in-out' as any,
  },
  operationsFilterActive: { backgroundColor: 'rgba(240,68,95,.12)', borderColor: 'rgba(240,68,95,.42)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,.065), 0 6px 18px rgba(240,68,95,.1)' as any },
  operationsFilterText: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 11, fontWeight: '900' },
  operationsFilterCount: { color: portalPalette.text, fontFamily: Typography.mono, fontSize: 11, fontWeight: '900', opacity: 0.8 },
  filterStatusDot: { backgroundColor: portalPalette.muted, borderRadius: 4, height: 7, width: 7 },
  filterStatusRunning: { backgroundColor: portalPalette.success },
  filterStatusStopped: { backgroundColor: portalPalette.danger },
  filterStatusOffRoute: { backgroundColor: portalPalette.warning },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 12,
    minWidth: 0,
    rowGap: 8,
  },
  headerActionButton: {
    boxShadow: 'none' as any,
  },
  notice: {
    alignItems: 'center',
    backgroundColor: portalPalette.warningSoft,
    borderColor: portalPalette.warning,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    padding: 12,
  },
  noticeText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 13,
    minWidth: 0,
  },
  noticeInline: {
    color: portalPalette.warning,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
  },
  onboardingPrompt: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minWidth: 0,
  },
  onboardingTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
    minWidth: 0,
  },
  operationsGrid: {
    alignItems: 'stretch',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minWidth: 0,
  },
  headerAction: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  mainOperationsGrid: {
    alignContent: 'stretch',
    alignItems: 'stretch',
    display: 'grid' as any,
    flex: 1,
    gap: 0,
    gridTemplateColumns: 'minmax(0, 1fr)' as any,
    gridTemplateRows: 'minmax(0, 1fr)' as any,
    minHeight: 0,
    minWidth: 0,
  },
  mainOperationsGridSelected: {
    gridTemplateColumns: `minmax(0, 1fr) ${OPERATIONS_DETAIL_WIDTH}px` as any,
  },
  operationsMapCol: {
    display: 'flex' as any,
    gap: 8,
    flexDirection: 'column',
    minHeight: 0,
    minWidth: 0,
  },
  operationsUnitsCol: {
    display: 'flex' as any,
    height: '100%',
    minHeight: 0,
    minWidth: 0,
    overflow: 'hidden',
  },
  operationsDetailSurface: {
    backgroundColor: 'rgba(12,21,35,.97)',
    borderColor: 'rgba(148,163,184,.16)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    height: '100%',
    minHeight: 0,
    overflowY: 'auto' as any,
    paddingHorizontal: AppTheme.spacing.lg,
    paddingVertical: AppTheme.spacing.md,
    boxShadow: '-14px 0 34px rgba(0,0,0,.18), inset 1px 0 0 rgba(255,255,255,.025)' as any,
  },
  kpiRow: {
    backgroundColor: 'rgba(10,19,33,.82)', borderColor: 'rgba(148,163,184,.12)',
    borderTopLeftRadius: 10, borderTopRightRadius: 0, borderBottomRightRadius: 0, borderBottomLeftRadius: 10,
    borderWidth: 1, borderRightWidth: 0, flexShrink: 0, minWidth: 0, overflowX: 'auto' as any, overflowY: 'hidden' as any, paddingBottom: AppTheme.spacing.xs,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,.025)' as any,
  },
  kpiTrack: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    minWidth: '100%' as any,
  },
  kpiCard: {
    backgroundColor: 'transparent', borderRightColor: 'rgba(148,163,184,.1)', borderRightWidth: 1, flex: 1, flexBasis: AppTheme.spacing.xxl * 3 + AppTheme.spacing.lg, gap: 3, minHeight: 76,
    minWidth: AppTheme.spacing.xxl * 3 + AppTheme.spacing.lg, paddingHorizontal: 12, paddingVertical: 8,
    animation: 'operationsFadeIn 220ms ease-in-out both' as any,
  },
  kpiCardLast: { borderRightWidth: 0 },
  kpiTop: { alignItems: 'center', flexDirection: 'row', gap: 6, minWidth: 0 },
  kpiLabel: { color: portalPalette.muted, flexShrink: 1, fontFamily: Typography.body, fontSize: 11, fontWeight: '800', letterSpacing: 0.15 },
  kpiValue: { color: '#FFFFFF', fontFamily: Typography.display, fontSize: 19, fontWeight: '900', letterSpacing: -0.25, lineHeight: 22 },
  kpiDetail: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 10, lineHeight: 14 },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minWidth: 0,
  },
  panelTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 16,
    fontWeight: '900',
  },
  primaryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 8,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  primaryText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  progressBlock: {
    gap: 3,
    paddingBottom: 7,
    paddingTop: 2,
  },
  progressFill: {
    backgroundColor: portalPalette.accent,
    borderRadius: 999,
    height: '100%',
    transition: 'width 220ms ease-in-out' as any,
  },
  progressTrack: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: 999,
    borderWidth: 1,
    height: 8,
    overflow: 'hidden',
  },
  progressValue: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  quickAction: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 10,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out, transform 180ms ease-in-out, opacity 180ms ease-in-out' as any,
  },
  quickActionHover: {
    backgroundColor: portalPalette.accentSoft,
    borderColor: portalPalette.lineStrong,
    transform: [{ translateY: -1 }],
  },
  quickActionText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
  },
  quickActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sideActions: {
    borderTopColor: 'rgba(148,163,184,.12)',
    borderTopWidth: 1,
    gap: 8,
    paddingTop: 8,
  },
  replayControls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  replayPanel: {
    flex: 1.2,
    flexBasis: 430,
    gap: 8,
    minWidth: 0,
  },
  replayEmptyNote: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    padding: 10,
  },
  replaySteps: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  routeIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(240,68,95,.16)',
    borderColor: 'rgba(240,68,95,.34)',
    borderWidth: 1,
    borderRadius: 16,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  routeSummaryLarge: {
    alignItems: 'flex-start',
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 2,
    paddingVertical: 8,
    boxShadow: 'none' as any,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out' as any,
  },
  routeTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    minHeight: 36,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  secondaryText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  sessionDetail: {
    gap: 12,
  },
  sideHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 8,
  },
  sideUnitIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(240,68,95,.14)',
    borderColor: 'rgba(240,68,95,.32)',
    borderRadius: 12,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  sideEyebrow: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.55,
    textTransform: 'uppercase',
  },
  sideMeta: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
  },
  sidePanel: {
    flex: 1,
    gap: AppTheme.spacing.md,
    animation: 'operationsFadeIn 200ms ease-in-out both' as any,
  },
  sideMetricGrid: {
    alignContent: 'center',
    flexGrow: 1,
  },
  recentTimeline: {
    gap: 0,
  },
  recentTimelineDot: {
    backgroundColor: portalPalette.info,
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  recentTimelineItem: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    transition: 'background-color 180ms ease-in-out, transform 180ms ease-in-out' as any,
  },
  recentTimelineRail: {
    alignItems: 'center',
    borderLeftColor: portalPalette.info,
    borderLeftWidth: 2,
    marginLeft: 5,
    paddingTop: 4,
    width: 12,
  },
  sideSectionTitle: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.45,
    marginTop: AppTheme.spacing.xs,
    textTransform: 'uppercase',
  },
  sideHighlightRow: {
    borderBottomColor: 'rgba(148,163,184,.12)',
    borderBottomWidth: 1,
    borderTopColor: 'rgba(148,163,184,.12)',
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: AppTheme.spacing.sm,
    minWidth: 0,
    paddingVertical: AppTheme.spacing.sm,
  },
  sideTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
  },
  sliderFill: {
    backgroundColor: portalPalette.accent,
    borderRadius: 999,
    height: '100%',
  },
  sliderTrack: {
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: 999,
    height: 8,
    overflow: 'hidden',
  },
  timelineDot: {
    alignItems: 'center',
    backgroundColor: portalPalette.info,
    borderRadius: 15,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  timelineItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timelineList: {
    gap: 8,
  },
  timelinePanel: {
    flex: 1,
    flexBasis: 320,
    gap: 10,
    minWidth: 0,
  },
  timelineTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  unitCard: {
    backgroundColor: 'transparent',
    borderColor: portalPalette.line,
    borderBottomWidth: 1,
    gap: 2,
    height: AppTheme.spacing.xxl * 2,
    minWidth: 0,
    paddingHorizontal: AppTheme.spacing.xs,
    paddingVertical: AppTheme.spacing.xs,
    transition: 'background-color 180ms ease-in-out, border-color 180ms ease-in-out, transform 180ms ease-in-out' as any,
  },
  unitCardActive: {
    backgroundColor: portalPalette.infoSoft,
    borderColor: portalPalette.accent,
  },
  unitCardHover: {
    backgroundColor: portalPalette.surfaceSoft,
    transform: [{ translateX: 2 }],
  },
  unitCode: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 16,
    fontWeight: '900',
  },
  unitHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'space-between',
  },
  mapOverlaySurface: {
    backgroundColor: 'rgba(5, 12, 25, 0.9)',
    borderColor: 'rgba(148,163,184,.24)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    backdropFilter: 'blur(16px)' as any,
    boxShadow: '0 20px 48px rgba(0,0,0,.44), inset 0 1px 0 rgba(255,255,255,.05)' as any,
    padding: AppTheme.spacing.sm,
  },
  unitSelectorOverlay: {
    gap: AppTheme.spacing.xs,
    left: AppTheme.spacing.md,
    maxHeight: AppTheme.spacing.xxl * 7 + AppTheme.spacing.lg,
    overflow: 'auto' as any,
    position: 'absolute',
    top: AppTheme.spacing.md,
    width: OPERATIONS_UNIT_SELECTOR_WIDTH,
  },
  filtersOverlayLane: {
    alignItems: 'center',
    left: OPERATIONS_UNIT_SELECTOR_WIDTH + AppTheme.spacing.md * 2,
    position: 'absolute',
    right: AppTheme.spacing.xxl + AppTheme.spacing.md,
    top: AppTheme.spacing.md,
  },
  filtersOverlay: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: AppTheme.spacing.xs,
    justifyContent: 'center',
    maxWidth: '100%',
    minWidth: 0,
  },
  mapOverlayTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 14,
    fontWeight: '900',
    lineHeight: AppTheme.spacing.lg,
  },
  unitSelectorHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: AppTheme.spacing.xs,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  unitSelectorHeaderMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: AppTheme.spacing.xs,
  },
  unitSelectorCount: {
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.pill,
    color: portalPalette.text,
    fontFamily: Typography.mono,
    fontSize: 11,
    fontWeight: '900',
    minWidth: AppTheme.spacing.lg,
    paddingHorizontal: AppTheme.spacing.xs,
    textAlign: 'center',
  },
  unitSelectorCollapsed: {
    gap: 0,
  },
  unitMeta: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 17,
  },
  unitGpsMessage: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 10,
    lineHeight: 14,
  },
});
