import { StyleSheet, Platform } from 'react-native';

export const marketingPalettes = {
  light: {
    mode: 'light' as const,
    background: '#FFFFFF',
    backgroundAlt: '#F8FAFC',
    ink: '#0F172A',
    muted: '#475569',
    mutedSoft: '#94A3B8',
    line: '#E2E8F0',
    accent: '#E11D48',
    accentSoft: '#FFF1F2',
    success: '#10B981',
    successSoft: '#F0FDF4',
    blue: '#3B82F6',
    blueSoft: '#EFF6FF',
    card: '#FFFFFF',
    panel: '#F1F5F9',
  },
  dark: {
    mode: 'dark' as const,
    background: '#020617',
    backgroundAlt: '#0F172A',
    ink: '#F8FAFC',
    muted: '#94A3B8',
    mutedSoft: '#475569',
    line: '#1E293B',
    accent: '#F43F5E',
    accentSoft: 'rgba(244, 63, 94, 0.15)',
    success: '#34D399',
    successSoft: 'rgba(52, 211, 153, 0.15)',
    blue: '#60A5FA',
    blueSoft: 'rgba(96, 165, 250, 0.15)',
    card: '#0F172A',
    panel: '#1E293B',
  },
} as const;

export type MarketingPalette = (typeof marketingPalettes)[keyof typeof marketingPalettes];

export function createStyles(palette: MarketingPalette, isCompact: boolean, isPhone: boolean, width: number) {
  return StyleSheet.create({
    screen: { flex: 1 },
    scroll: { flex: 1 },
    content: { paddingBottom: 100, maxWidth: '100%', overflow: 'hidden' },
    navbar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 24, maxWidth: 1240, alignSelf: 'center', width: '100%' },
    brand: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    brandBadge: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    brandTitle: { fontSize: 22, fontWeight: '900', letterSpacing: -0.5 },
    navActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    navGhost: { height: 44, paddingHorizontal: 16, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
    navGhostText: { fontWeight: '700' },
    navPrimary: { height: 44, paddingHorizontal: 20, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    navPrimaryText: { color: '#FFF', fontWeight: '800' },
    hero: { flexDirection: 'row', padding: 24, maxWidth: 1240, alignSelf: 'center', gap: 60, marginTop: 40, alignItems: 'center' },
    heroCompact: { flexDirection: 'column', gap: 40 },
    heroLeft: { flex: 1.2, gap: 24, width: '100%' },
    heroTag: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 6, borderRadius: 8 },
    heroTagText: { fontSize: 11, fontWeight: '900', letterSpacing: 1, textTransform: 'uppercase' },
    heroTitle: { fontSize: Platform.OS === 'web' ? 48 : 36, fontWeight: '900', lineHeight: Platform.OS === 'web' ? 56 : 44, letterSpacing: -1.5 },
    heroSubtitle: { fontSize: 18, lineHeight: 28 },
    heroFeatures: { gap: 14 },
    heroFeatureItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    heroFeatureText: { fontSize: 15, fontWeight: '600' },
    heroButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginTop: 10 },
    heroBtnPrimary: { height: 60, paddingHorizontal: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', elevation: 10, shadowOpacity: 0.2 },
    heroBtnPrimaryText: { color: '#FFF', fontWeight: '900', fontSize: 16 },
    heroBtnSecondary: { height: 60, paddingHorizontal: 28, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
    heroBtnSecondaryText: { fontWeight: '800', fontSize: 16 },
    heroRight: { flex: 1, width: '100%' },
    heroVisualCard: { borderRadius: 32, padding: 32, borderWidth: 1, elevation: 20, shadowOpacity: 0.1 },
    visualHeader: { gap: 4, marginBottom: 20 },
    visualOverline: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
    visualTitle: { fontSize: 32, fontWeight: '900' },
    visualPrice: { fontSize: 48, fontWeight: '900' },
    visualFreq: { fontSize: 16, fontWeight: '400' },
    visualDivider: { height: 1, marginVertical: 24 },
    visualGrid: { gap: 20 },
    vMetric: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    vIcon: { width: 44, height: 44, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
    vLabel: { fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
    vValue: { fontSize: 16, fontWeight: '800' },
    section: { padding: 24, maxWidth: 1240, alignSelf: 'center', width: '100%', marginTop: 80 },
    sectionHeader: { gap: 10, marginBottom: 40 },
    eyebrow: { fontSize: 13, fontWeight: '900', letterSpacing: 2 },
    sectionTitle: { fontSize: 36, fontWeight: '900', letterSpacing: -1 },
    featureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 },
    featureCard: { flex: 1, minWidth: 260, borderRadius: 24, padding: 24, borderWidth: 1, gap: 16 },
    featureIcon: { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
    featureTitle: { fontSize: 18, fontWeight: '800' },
    featureBody: { fontSize: 15, lineHeight: 24 },
    plansTrack: { paddingHorizontal: 24, paddingBottom: 40, gap: 24 },
    pCard: { borderRadius: 32, borderWidth: 2, overflow: 'hidden', elevation: 15, shadowOpacity: 0.1 },
    pHeader: { padding: 14, alignItems: 'center' },
    pTitle: { fontSize: 15, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1 },
    pBody: { padding: 28, gap: 20 },
    pPrice: { fontSize: 40, fontWeight: '900' },
    pFreq: { fontSize: 14, fontWeight: '400' },
    pSubtitle: { fontSize: 13, lineHeight: 20 },
    pDivider: { height: 1 },
    pFeatures: { gap: 14 },
    fItem: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    fText: { fontSize: 14, fontWeight: '600' },
    pAction: { height: 56, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 10 },
    pActionText: { fontWeight: '800', fontSize: 16 },
    checkoutWrap: { padding: 32, maxWidth: 1100, alignSelf: 'center', width: '100%', marginTop: 80, borderRadius: 40, borderWidth: 1 },
    checkoutGrid: { flexDirection: Platform.OS === 'web' && width > 900 ? 'row' : 'column', gap: 40 },
    checkoutFormSide: { flex: 1.2, gap: 24, width: '100%' },
    checkoutTitle: { fontSize: 28, fontWeight: '900' },
    checkoutSubtitle: { fontSize: 15, lineHeight: 24 },
    authToggle: { flexDirection: 'row', padding: 6, borderRadius: 14 },
    authTab: { flex: 1, height: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
    authTabText: { fontWeight: '800', fontSize: 14 },
    inputGrid: { gap: 16 },
    field: { gap: 8 },
    inputLabel: { fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5, marginLeft: 4 },
    input: { height: 56, borderRadius: 14, borderWidth: 2, paddingHorizontal: 16, fontSize: 15, fontWeight: '600' },
    paymentMethods: { gap: 10 },
    paymentCard: { flexDirection: 'row', padding: 16, borderRadius: 18, borderWidth: 2, alignItems: 'center', gap: 14 },
    paymentLabel: { fontSize: 15, fontWeight: '800' },
    paymentHelper: { fontSize: 12 },
    msg: { padding: 16, borderRadius: 16, borderWidth: 1, alignItems: 'center' },
    submitBtn: { height: 68, borderRadius: 18, alignItems: 'center', justifyContent: 'center', elevation: 12, shadowOpacity: 0.3 },
    submitBtnText: { color: '#FFF', fontWeight: '900', fontSize: 18 },
    checkoutSummarySide: { flex: 0.8, borderRadius: 32, padding: 32, borderWidth: 1, gap: 24, width: '100%' },
    summaryTitle: { fontSize: 22, fontWeight: '900' },
    summarySteps: { gap: 20 },
    stepsTitle: { fontSize: 16, fontWeight: '800' },
    stepItem: { flexDirection: 'row', gap: 14 },
    stepDot: { width: 10, height: 10, borderRadius: 5, marginTop: 6 },
    stepText: { fontSize: 14, fontWeight: '800' },
    stepDesc: { fontSize: 13, lineHeight: 20 },
    faqGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 20 },
    faqCard: { flex: 1, minWidth: 260, padding: 24, borderRadius: 24, borderWidth: 1, gap: 12 },
    faqQ: { fontSize: 16, fontWeight: '800' },
    faqA: { fontSize: 14, lineHeight: 22 },
    footer: { marginTop: 100, padding: 40, borderTopWidth: 1, alignItems: 'center' },
    footerLinks: { flexDirection: 'row', gap: 16 },
    footerBtn: { height: 50, paddingHorizontal: 24, borderRadius: 12, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
    footerBtnText: { fontSize: 14, fontWeight: '800' },
  });
}
