import { StyleSheet } from 'react-native';
import { Typography } from '@/constants/theme';

export const mapStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  root: { flex: 1 },
  topOverlay: { position: 'absolute', top: 0, left: 0, right: 0, paddingHorizontal: 14, zIndex: 10 },
  topBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, minWidth: 0 },
  iconButton: { width: 42, height: 42, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  hud: { flex: 1, minHeight: 42, borderRadius: 13, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minWidth: 0, paddingHorizontal: 9 },
  hudItem: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 6, minWidth: 0 },
  hudTextBlock: { flex: 1, minWidth: 0 },
  hudLabel: { flexShrink: 1, fontSize: 9, fontWeight: '700', fontFamily: Typography.body, minWidth: 0, textTransform: 'uppercase' },
  hudValue: { flexShrink: 1, fontSize: 13, fontWeight: '800', fontFamily: Typography.mono, minWidth: 0 },
  sideActions: { position: 'absolute', right: 14, gap: 8, zIndex: 10 },
  fabGroup: { borderRadius: 15, borderWidth: 1, overflow: 'hidden', elevation: 6, shadowOpacity: 0.12, shadowRadius: 8 },
  fabCompact: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  fabDivider: { height: StyleSheet.hairlineWidth, marginHorizontal: 8 },
  fab: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, alignItems: 'center', justifyContent: 'center', elevation: 6, shadowOpacity: 0.12, shadowRadius: 8 },
  controlPressed: { opacity: 0.88, transform: [{ scale: 0.94 }] },
  selectorPanel: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 30,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    elevation: 8,
    shadowOpacity: 0.12,
    shadowRadius: 10,
  },
  selectorStepBadge: {
    minWidth: 54,
    minHeight: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EAF2FF',
  },
  selectorStepText: {
    color: '#1473E6',
    fontSize: 12,
    fontWeight: '900',
    fontFamily: Typography.body,
  },
  selectorCopy: { flex: 1, minWidth: 0, gap: 2 },
  selectorTitle: { fontSize: 14, fontWeight: '900', fontFamily: Typography.display },
  selectorHint: { fontSize: 11, lineHeight: 15, fontFamily: Typography.body },
  selectorEditWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    zIndex: 30,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selectorEditChip: {
    minHeight: 34,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
  },
  selectorEditText: {
    fontSize: 12,
    fontWeight: '900',
    fontFamily: Typography.body,
  },
  selectorConfirmWrap: { position: 'absolute', left: 16, right: 16, zIndex: 30 },
  selectorUndoButton: {
    minHeight: 40,
    borderRadius: 13,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  selectorUndoText: { fontSize: 12, fontWeight: '900', fontFamily: Typography.body },
  selectorConfirmButton: {
    minHeight: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
  },
  selectorConfirmDisabled: { opacity: 0.78 },
  selectorConfirmText: { color: '#FFFFFF', fontSize: 14, fontWeight: '900', fontFamily: Typography.body },
  bottomOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, gap: 8, paddingHorizontal: 14, zIndex: 10 },
  locationNotice: {
    alignSelf: 'center',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    maxWidth: 440,
    paddingHorizontal: 12,
    paddingVertical: 9,
    width: '100%',
  },
  locationNoticeCopy: { flex: 1, gap: 2, minWidth: 0 },
  locationNoticeTitle: { flexShrink: 1, fontSize: 13, fontWeight: '900', fontFamily: Typography.body, minWidth: 0 },
  locationNoticeText: { flexShrink: 1, fontSize: 11, lineHeight: 15, fontFamily: Typography.body, minWidth: 0 },
  locationRetry: { width: 38, height: 38, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  followCard: { borderRadius: 18, borderWidth: 1, padding: 12, gap: 10, elevation: 8, shadowOpacity: 0.12, shadowRadius: 10 },
  trackingPanelCard: { overflow: 'hidden' },
  panelHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, marginBottom: 1 },
  followHeader: { flexDirection: 'row', gap: 10, justifyContent: 'space-between', alignItems: 'center', minWidth: 0 },
  followIdentity: { flex: 1, minWidth: 0 },
  followMetrics: { flexDirection: 'row', alignItems: 'center', gap: 6, flexShrink: 0 },
  followTitle: { flexShrink: 1, fontSize: 19, fontWeight: '800', fontFamily: Typography.display, minWidth: 0 },
  followMeta: { fontSize: 12, fontFamily: Typography.body, minWidth: 0 },
  compactStatusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 'auto' },
  compactGpsStatus: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 6 },
  compactGpsText: { flex: 1, minWidth: 0, fontSize: 12, fontWeight: '800', fontFamily: Typography.body },
  expandButton: { minHeight: 34, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingHorizontal: 4 },
  expandedPanelScroll: { flexGrow: 0 },
  expandedPanelContent: { gap: 10, paddingBottom: 4 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  metricCard: { width: '48%', minHeight: 66, borderRadius: 12, padding: 9, gap: 2 },
  metricLabel: { fontSize: 10, fontWeight: '700', fontFamily: Typography.body },
  metricValue: { fontSize: 13, fontWeight: '900', fontFamily: Typography.body },
  detailsButton: {
    minHeight: 38,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
  },
  detailsButtonText: { fontSize: 12, fontWeight: '900', fontFamily: Typography.body },
  detailsPanel: { borderTopWidth: 1, gap: 8, paddingTop: 10 },
  panelActionRow: { flexDirection: 'row', gap: 8 },
  panelActionButton: { flex: 1 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, minWidth: 0 },
  detailLabel: { flex: 1, fontSize: 11, fontWeight: '700', fontFamily: Typography.body, minWidth: 0 },
  detailValue: { flex: 1.4, fontSize: 12, fontWeight: '800', fontFamily: Typography.body, minWidth: 0, textAlign: 'right' },
  alertStrip: {
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  alertCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  alertTitle: {
    color: '#FFF',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
    fontFamily: Typography.body,
    minWidth: 0,
  },
  alertMeta: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 11,
    fontFamily: Typography.body,
  },
  trackList: { gap: 8, paddingRight: 2 },
  trackChip: { minHeight: 36, paddingHorizontal: 13, paddingVertical: 8, borderRadius: 11, borderWidth: 1 },
  trackChipTitle: { fontSize: 13, fontWeight: '800', fontFamily: Typography.body },
  trackChipTitleSelected: { color: '#FFF' },
  emptyTrackState: { minHeight: 36, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 4 },
  emptyTrackText: { fontSize: 12, fontWeight: '700', fontFamily: Typography.body },
  historyBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  historyCard: { maxHeight: '82%', borderTopLeftRadius: 22, borderTopRightRadius: 22, borderWidth: 1, padding: 16, gap: 12 },
  historyList: { gap: 10, paddingBottom: 24 },
  historyItem: { minHeight: 62, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  historyBack: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', paddingVertical: 6 },
  inlineHistory: { borderTopWidth: 1, gap: 8, paddingTop: 10 },
  historyItemTitle: { textAlign: 'left' },
  historyDetailsButton: { minHeight: 34, borderRadius: 11, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  vehicleMarker: { width: 20, height: 20, borderRadius: 10, borderWidth: 3, borderColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  vehicleMarkerInner: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#FFF' },
  incidentMarker: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  selectorPointMarker: { width: 42, height: 30, borderRadius: 15, borderWidth: 2, borderColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  selectorPointMarkerText: { color: '#FFF', fontSize: 11, fontWeight: '900', fontFamily: Typography.body },
  userMarker: { width: 20, height: 20, borderRadius: 10, borderWidth: 3, borderColor: '#FFF' },
  selectorStopMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowOpacity: 0.16,
    shadowRadius: 5,
  },
  stopMarkerText: { color: '#FFFFFF', fontSize: 11, fontWeight: '900', fontFamily: Typography.body },
  recoveryRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 28,
  },
  recoveryIcon: {
    width: 62,
    height: 62,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recoveryTitle: {
    fontFamily: Typography.display,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  recoveryMessage: {
    maxWidth: 420,
    fontFamily: Typography.body,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  recoveryActions: {
    width: '100%',
    maxWidth: 320,
    gap: 10,
    marginTop: 8,
  },
  recoveryPrimaryButton: {
    minHeight: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  recoveryPrimaryText: {
    color: '#FFF',
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '800',
  },
  recoverySecondaryButton: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  recoverySecondaryText: {
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '700',
  },
  recoveryGhostButton: {
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  recoveryGhostText: {
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '700',
  },
  recoveryPressed: {
    opacity: 0.86,
  },
  recoveryDisabled: {
    opacity: 0.64,
  },
});
