import { Platform, StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import type { useAppTheme } from '@/src/hooks/use-app-theme';

export function createStyles(theme: ReturnType<typeof useAppTheme>['theme'], isCompact: boolean, isPhone: boolean) {
  return StyleSheet.create({
    header: {
      gap: 8,
      paddingTop: isPhone ? AppTheme.spacing.sm : AppTheme.spacing.md,
    },
    title: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 26 : 30,
      fontWeight: '900',
    },
    mainGrid: {
      flexDirection: Platform.OS === 'web' && !isCompact ? 'row' : 'column',
      gap: AppTheme.spacing.md,
      alignItems: 'stretch',
      width: '100%',
    },
    identityBlock: {
      gap: 14,
      maxWidth: 680,
      zIndex: 2,
    },
    profileTop: {
      alignItems: isPhone ? 'flex-start' : 'center',
      flexDirection: isPhone ? 'column' : 'row',
      gap: 14,
    },
    avatarBox: {
      borderColor: theme.colors.accent,
      borderRadius: 66,
      borderWidth: 2,
      padding: 5,
    },
    profileCopy: {
      flex: 1,
      minWidth: 0,
      gap: 8,
    },
    userName: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 24 : 31,
      fontWeight: '900',
      letterSpacing: -0.8,
    },
    pillsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    sideColumn: {
      flex: 0.92,
      gap: AppTheme.spacing.md,
      width: isCompact ? '100%' : undefined,
      minWidth: isPhone ? 0 : 340,
    },
    cardTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
      fontWeight: '900',
    },
    infoGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    infoTile: {
      backgroundColor: theme.colors.surfaceAlt,
      borderColor: theme.colors.line,
      borderRadius: AppTheme.radius.sm2,
      borderWidth: 1,
      flex: 1,
      gap: 8,
      minWidth: isPhone ? '100%' : 220,
      padding: 13,
      zIndex: 2,
    },
    infoIcon: {
      alignItems: 'center',
      backgroundColor: theme.colors.accentSoft,
      borderRadius: AppTheme.radius.xs3,
      height: 42,
      justifyContent: 'center',
      width: 42,
    },
    infoLabel: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    infoValue: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '800',
      lineHeight: 21,
      flexShrink: 1,
    },
    themeRow: {
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.line,
      borderRadius: AppTheme.radius.sm,
      flexDirection: 'row',
      gap: 8,
      padding: 6,
    },
    themeTab: {
      alignItems: 'center',
      borderColor: 'transparent',
      borderRadius: 13,
      borderWidth: 1,
      flex: 1,
      flexDirection: 'row',
      gap: 8,
      height: 42,
      justifyContent: 'center',
    },
    themeTabText: {
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '900',
    },
    sessionCard: {
      backgroundColor: theme.colors.cardSoft,
      borderColor: theme.colors.line,
    },
    notificationList: {
      gap: 8,
    },
    notificationRow: {
      minHeight: 58,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    notificationIcon: {
      width: 36,
      height: 36,
      borderRadius: AppTheme.radius.xs2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    notificationCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    notificationTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '900',
    },
    notificationBody: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 17,
    },
    driverRow: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceAlt,
      borderColor: theme.colors.line,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 58,
      padding: 10,
    },
    driverCopy: {
      flex: 1,
      gap: 3,
      minWidth: 0,
    },
    documentDetail: {
      borderLeftColor: theme.colors.line,
      borderLeftWidth: 2,
      gap: 8,
      marginLeft: 17,
      paddingLeft: 18,
    },
    driverDocumentBlock: {
      gap: 8,
    },
    documentActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'flex-end',
    },
    documentActionButton: {
      alignItems: 'center',
      borderColor: theme.colors.accent,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 36,
      minWidth: 104,
      paddingHorizontal: 12,
    },
    documentActionText: {
      color: theme.colors.accent,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '900',
    },
    documentReviewNote: {
      color: theme.colors.danger,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 17,
      paddingHorizontal: 10,
    },
    documentExpiryInput: {
      backgroundColor: theme.colors.surfaceAlt,
      borderColor: theme.colors.line,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      minHeight: 44,
      paddingHorizontal: 12,
    },
    documentUploadButton: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent,
      borderRadius: AppTheme.radius.xs3,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 14,
    },
    documentUploadText: {
      color: AppTheme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '900',
    },
    documentMessage: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 17,
    },
    emptyNotifications: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 13,
      lineHeight: 19,
    },
    logoutBtn: {
      alignItems: 'center',
      borderColor: theme.colors.accent,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1.5,
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      minHeight: 46,
    },
    logoutText: {
      color: theme.colors.accent,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '900',
    },
  });
}
