import { Platform, StyleSheet } from 'react-native';
import { Typography } from '@/constants/theme';
import { neonPalette } from './constants';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: neonPalette.background,
    ...(Platform.OS === 'web'
      ? ({ minHeight: '100vh', overflow: 'visible' } as any)
      : { overflow: 'hidden' as const }),
  },
  scroll: {
    flex: 1,
  },
  webPage: {
    minHeight: '100vh' as any,
    overflowX: 'hidden' as any,
    width: '100%',
  },
  content: {
    paddingBottom: 36,
    paddingTop: 96,
  },
  container: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingTop: 112,
    paddingBottom: 36,
    gap: 78,
  },
  checkoutReturnBanner: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: -34,
    minWidth: 0,
    padding: 14,
  },
  checkoutReturnIcon: {
    alignItems: 'center',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  checkoutReturnCopy: {
    flex: 1,
    flexBasis: 260,
    gap: 3,
    minWidth: 0,
  },
  checkoutReturnTitle: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  checkoutReturnBody: {
    color: neonPalette.mutedStrong,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  checkoutReturnButton: {
    alignItems: 'center',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
  },
  checkoutReturnButtonText: {
    color: '#050816',
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  containerPhone: {
    paddingHorizontal: 16,
    paddingTop: 132,
    gap: 58,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  animatedWash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: neonPalette.background,
  },
  parallaxField: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundOrb: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.75,
  },
  backgroundOrbBlue: {
    top: 96,
    left: -160,
    width: 460,
    height: 460,
    backgroundColor: 'rgba(0, 194, 255, 0.16)',
  },
  backgroundOrbPink: {
    top: -140,
    right: -140,
    width: 520,
    height: 520,
    backgroundColor: 'rgba(255, 45, 122, 0.18)',
  },
  backgroundOrbViolet: {
    right: -220,
    bottom: 220,
    width: 600,
    height: 600,
    backgroundColor: 'rgba(122, 60, 255, 0.14)',
  },
  routeField: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.74,
  },
  routeLine: {
    position: 'absolute',
    left: -160,
    right: -160,
    height: 1,
    backgroundColor: 'rgba(0, 194, 255, 0.12)',
  },
  particleField: {
    ...StyleSheet.absoluteFillObject,
  },
  particle: {
    position: 'absolute',
    width: 3,
    height: 3,
    borderRadius: 2,
    opacity: 0.68,
  },
  headerShell: {
    position: Platform.OS === 'web' ? ('fixed' as any) : 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    minHeight: 76,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(245, 247, 255, 0.09)',
    backgroundColor: 'rgba(5, 8, 22, 0.66)',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  headerShellCompact: {
    minHeight: 60,
    paddingVertical: 8,
    backgroundColor: 'rgba(5, 8, 22, 0.78)',
  },
  headerShellPhone: {
    minHeight: 116,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  headerInner: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  headerInnerPhone: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  headerNav: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  headerNavScroll: {
    width: '100%',
    flexGrow: 0,
  },
  headerNavPhoneContent: {
    alignItems: 'center',
    gap: 6,
    justifyContent: 'space-between',
    minWidth: '100%' as any,
    paddingRight: 0,
  },
  navItem: {
    minHeight: 38,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  navItemPhone: {
    minHeight: 32,
    paddingHorizontal: 7,
  },
  navItemHover: {
    backgroundColor: 'rgba(0, 194, 255, 0.08)',
    borderColor: 'rgba(0, 194, 255, 0.22)',
    transform: [{ translateY: -1 }],
  },
  navItemText: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
  },
  navItemTextPhone: {
    fontSize: 10.5,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  heroSection: {
    minHeight: 650,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 255, 0.09)',
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 28,
    gap: 26,
  },
  heroDesktop: {
    minHeight: 650,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 34,
    paddingVertical: 34,
  },
  heroPhone: {
    minHeight: 720,
    paddingHorizontal: 14,
    paddingTop: 28,
  },
  heroTablet: {
    minHeight: 560,
    paddingHorizontal: 30,
    paddingVertical: 36,
    gap: 30,
  },
  heroCopy: {
    flex: 0.92,
    maxWidth: 580,
    gap: 20,
    zIndex: 2,
  },
  heroCopyPhone: {
    maxWidth: '100%' as any,
    gap: 16,
  },
  heroKicker: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 45, 122, 0.42)',
    backgroundColor: neonPalette.accentSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 12,
  },
  heroKickerText: {
    color: neonPalette.accent,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  heroTitle: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 58,
    lineHeight: 64,
    fontWeight: '900',
    maxWidth: 620,
  },
  heroTitlePhone: {
    fontSize: 36,
    lineHeight: 42,
  },
  heroTitleTablet: {
    fontSize: 46,
    lineHeight: 52,
  },
  heroSubtitle: {
    color: neonPalette.mutedStrong,
    fontFamily: Typography.body,
    fontSize: 17,
    lineHeight: 27,
    maxWidth: 560,
  },
  heroSubtitlePhone: {
    fontSize: 14.5,
    lineHeight: 22,
  },
  heroSubtitleTablet: {
    fontSize: 15.5,
    lineHeight: 24,
  },
  heroActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 8,
  },
  actionButton: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    minWidth: 0,
  },
  actionButtonCompact: {
    minHeight: 42,
    paddingHorizontal: 10,
  },
  actionButtonSolid: {
    backgroundColor: neonPalette.accent,
    borderColor: neonPalette.accent,
    ...(Platform.OS === 'web'
      ? {}
      : {
          shadowColor: neonPalette.accent,
          shadowOpacity: 0.36,
          shadowRadius: 18,
          shadowOffset: { width: 0, height: 8 },
          elevation: 5,
        }),
  },
  actionButtonGhost: {
    backgroundColor: 'rgba(245, 247, 255, 0.055)',
    borderColor: 'rgba(245, 247, 255, 0.16)',
  },
  actionButtonText: {
    color: neonPalette.text,
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 13.5,
    fontWeight: '900',
    minWidth: 0,
  },
  actionButtonTextSolid: {
    color: '#FFFFFF',
  },
  heroVisual: {
    flex: 1.1,
    minHeight: 470,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  heroVisualPhone: {
    minHeight: 360,
    width: '100%',
  },
  dashboardFrame: {
    width: '94%',
    maxWidth: 620,
    aspectRatio: 1.48,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(0, 194, 255, 0.32)',
    backgroundColor: 'rgba(7, 13, 30, 0.9)',
    flexDirection: 'row',
    overflow: 'hidden',
  },
  dashboardFramePhone: {
    width: '100%',
    aspectRatio: 1.24,
  },
  dashboardSidebar: {
    width: '27%',
    minWidth: 88,
    borderRightWidth: 1,
    borderRightColor: 'rgba(245, 247, 255, 0.08)',
    backgroundColor: 'rgba(5, 8, 22, 0.76)',
    padding: 12,
    gap: 11,
  },
  dashboardMiniBrand: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  },
  dashboardNavRow: {
    minHeight: 24,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 8,
  },
  dashboardNavRowActive: {
    backgroundColor: 'rgba(0, 194, 255, 0.1)',
  },
  dashboardNavDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(138, 147, 178, 0.5)',
  },
  dashboardNavDotActive: {
    backgroundColor: neonPalette.cyan,
  },
  dashboardNavText: {
    color: neonPalette.mutedStrong,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '800',
  },
  dashboardMain: {
    flex: 1,
    padding: 14,
    gap: 12,
  },
  dashboardTopbar: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  dashboardTitle: {
    color: neonPalette.text,
    flex: 1,
    fontFamily: Typography.display,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 16,
  },
  dashboardStatus: {
    minHeight: 24,
    borderRadius: 999,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(47, 255, 213, 0.1)',
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: neonPalette.mint,
  },
  dashboardStatusText: {
    color: neonPalette.mint,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '900',
  },
  mapPanel: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0, 194, 255, 0.18)',
    backgroundColor: 'rgba(8, 14, 33, 0.92)',
    overflow: 'hidden',
    position: 'relative',
  },
  mapGrid: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.22,
    backgroundColor: 'rgba(0, 194, 255, 0.04)',
  },
  mapRoute: {
    position: 'absolute',
    left: '10%' as any,
    right: '12%' as any,
    height: 3,
    borderRadius: 999,
  },
  mapRouteCyan: {
    top: '34%' as any,
    backgroundColor: 'rgba(0, 194, 255, 0.58)',
    transform: [{ rotate: '-9deg' }],
  },
  mapRoutePink: {
    top: '52%' as any,
    backgroundColor: 'rgba(255, 45, 122, 0.62)',
    transform: [{ rotate: '13deg' }],
  },
  mapRouteViolet: {
    top: '70%' as any,
    backgroundColor: 'rgba(122, 60, 255, 0.55)',
    transform: [{ rotate: '-4deg' }],
  },
  vehiclePin: {
    position: 'absolute',
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingIndicator: {
    position: 'absolute',
    minWidth: 174,
    minHeight: 72,
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(7, 12, 30, 0.82)',
  },
  floatingIndicatorA: {
    left: -6,
    bottom: 44,
  },
  floatingIndicatorB: {
    right: 16,
    top: 58,
  },
  floatingIndicatorC: {
    right: -10,
    bottom: 96,
  },
  floatingIndicatorPhoneA: {
    left: 0,
    bottom: 4,
    minWidth: 148,
  },
  floatingIndicatorPhoneB: {
    right: 0,
    top: -18,
    minWidth: 148,
  },
  floatingIndicatorPhoneC: {
    right: 0,
    bottom: 88,
    minWidth: 148,
  },
  floatingIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  floatingValue: {
    fontFamily: Typography.display,
    fontSize: 22,
    fontWeight: '900',
  },
  floatingLabel: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
  },
  section: {
    gap: 28,
  },
  sectionHeading: {
    gap: 8,
    maxWidth: 680,
  },
  sectionHeadingCentered: {
    alignSelf: 'center',
    alignItems: 'center',
  },
  sectionCopy: {
    gap: 6,
    flex: 1,
  },
  sectionEyebrow: {
    color: neonPalette.accent,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
  },
  sectionTitle: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
    maxWidth: 680,
  },
  sectionTitleCentered: {
    textAlign: 'center',
  },
  sectionIntro: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 14.5,
    lineHeight: 23,
    maxWidth: 560,
  },
  sectionIntroCentered: {
    textAlign: 'center',
  },
  benefitGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
  },
  benefitGridPhone: {
    flexDirection: 'column',
  },
  benefitCard: {
    flexGrow: 1,
    flexBasis: 340,
    minHeight: 210,
    borderRadius: 8,
    borderWidth: 1,
    padding: 20,
    gap: 14,
    backgroundColor: 'rgba(9, 15, 34, 0.78)',
  },
  benefitCardPhone: {
    flexBasis: 'auto' as any,
    width: '100%',
  },
  benefitCardHover: {
    transform: [{ translateY: -5 }],
  },
  benefitIcon: {
    width: 52,
    height: 52,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  benefitTitle: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  benefitBody: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13.5,
    lineHeight: 21,
  },
  anchorOffset: {
    gap: 22,
  },
  plansHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 12,
    flexWrap: 'wrap',
  },
  carouselControls: {
    flexDirection: 'row',
    gap: 8,
  },
  roundButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(245, 247, 255, 0.065)',
    borderWidth: 1,
    borderColor: neonPalette.line,
  },
  roundButtonDisabled: {
    opacity: 0.42,
  },
  planCarouselViewport: {
    alignSelf: 'stretch',
    marginHorizontal: -18,
    marginTop: -18,
    maxWidth: '100%' as any,
    paddingHorizontal: 18,
    paddingTop: 18,
    width: '100%',
  },
  planCarouselViewportPhone: {
    marginHorizontal: 0,
    marginTop: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
  },
  planCarouselViewportDesktop: {
    alignSelf: 'center',
    marginHorizontal: 0,
    overflow: 'hidden',
    paddingHorizontal: 0,
    width: '100%',
  },
  planCarousel: {
    gap: 18,
    paddingLeft: 18,
    paddingRight: 30,
    paddingTop: 18,
    paddingBottom: 34,
  },
  planCarouselPhone: {
    gap: 12,
    paddingBottom: 22,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 8,
  },
  planCarouselDesktop: {
    gap: 18,
    paddingLeft: 0,
    paddingRight: 0,
  },
  planCardSkeleton: {
    backgroundColor: neonPalette.panel,
    borderColor: neonPalette.line,
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    padding: 20,
  },
  planSkeletonHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  planSkeletonRows: {
    gap: 10,
    marginTop: 2,
  },
  skeletonBar: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 8,
    overflow: 'hidden',
  },
  skeletonShine: {
    ...StyleSheet.absoluteFillObject,
    ...(({
      backgroundImage:
        'linear-gradient(100deg, transparent 20%, rgba(255,255,255,0.12) 50%, transparent 80%)',
    } as any)),
  },
  plansEmpty: {
    alignItems: 'center',
    borderColor: neonPalette.line,
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 1,
    gap: 8,
    marginTop: 8,
    padding: 28,
  },
  plansEmptyTitle: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  plansEmptyText: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 420,
    textAlign: 'center',
  },
  plansRetryButton: {
    borderColor: neonPalette.lineStrong,
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 6,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  plansRetryLabel: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '800',
  },
  planCard: {
    minHeight: 382,
    borderRadius: 16,
    borderWidth: 1.5,
    backgroundColor: 'rgba(12, 20, 42, 0.88)',
    padding: 20,
    gap: 15,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? {}
      : {
          shadowRadius: 30,
          shadowOffset: { width: 0, height: 16 },
          elevation: 8,
        }),
  },
  planSelectedHalo: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 16,
    borderWidth: 1,
    opacity: 0.8,
  },
  planTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  planBadge: {
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    ...(Platform.OS === 'web'
      ? {}
      : {
          textShadowOffset: { width: 0, height: 0 },
          textShadowRadius: 10,
        }),
  },
  planBadgeActive: {
    letterSpacing: 2.1,
  },
  planName: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? {}
      : {
          textShadowColor: 'rgba(255, 255, 255, 0.16)',
          textShadowOffset: { width: 0, height: 0 },
          textShadowRadius: 14,
        }),
  },
  planSymbol: {
    width: 46,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  planSubtitle: {
    color: 'rgba(207, 218, 235, 0.78)',
    fontFamily: Typography.body,
    fontSize: 13.5,
    lineHeight: 21,
    minHeight: 42,
  },
  planPriceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
  },
  planPrice: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 40,
    lineHeight: 46,
    fontWeight: '900',
    ...(Platform.OS === 'web'
      ? {}
      : {
          textShadowColor: 'rgba(255, 255, 255, 0.18)',
          textShadowOffset: { width: 0, height: 0 },
          textShadowRadius: 16,
        }),
  },
  planPeriod: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    marginBottom: 6,
    fontWeight: '800',
  },
  planList: {
    gap: 10,
    flex: 1,
  },
  planListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  planListText: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 13.5,
    lineHeight: 19,
    fontWeight: '800',
    flex: 1,
  },
  planActions: {
    gap: 10,
  },
  planButton: {
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  planButtonLabel: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
    minWidth: 0,
  },
  planTrialButton: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  planTrialLabel: {
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
    minWidth: 0,
  },
  planDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: -28,
  },
  planDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  planDotActive: {
    width: 22,
  },
  processRail: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 18,
    paddingHorizontal: 20,
  },
  processRailPhone: {
    flexDirection: 'column',
    paddingHorizontal: 0,
    gap: 22,
  },
  processStep: {
    flex: 1,
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
    position: 'relative',
  },
  processStepPhone: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  processNodeWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  processNode: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: 'rgba(9, 15, 34, 0.8)',
  },
  processNumber: {
    fontFamily: Typography.display,
    fontSize: 14,
    fontWeight: '900',
  },
  processConnector: {
    position: 'absolute',
    left: 118,
    top: 59,
    width: 150,
    height: 2,
    borderRadius: 999,
    backgroundColor: neonPalette.cyan,
  },
  processConnectorPhone: {
    left: 59,
    top: 118,
    width: 2,
    height: 48,
  },
  processTitle: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  processBody: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12.5,
    lineHeight: 19,
    textAlign: 'center',
    maxWidth: 190,
  },
  trustSection: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 255, 0.1)',
    backgroundColor: 'rgba(9, 15, 34, 0.8)',
    padding: 24,
    gap: 26,
    overflow: 'hidden',
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 18,
  },
  metricGridPhone: {
    flexDirection: 'column',
  },
  metricGridTablet: {
    flexWrap: 'wrap',
  },
  metricCardTablet: {
    flexBasis: '46%' as any,
    minWidth: 200,
  },
  metricCard: {
    flex: 1,
    minHeight: 122,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 255, 0.1)',
    backgroundColor: 'rgba(245, 247, 255, 0.045)',
    padding: 18,
    gap: 7,
  },
  metricIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  metricValue: {
    fontFamily: Typography.display,
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '900',
  },
  metricLabel: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '800',
  },
  faqShell: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(245, 247, 255, 0.1)',
    backgroundColor: 'rgba(9, 15, 34, 0.82)',
    padding: 22,
    gap: 24,
    overflow: 'hidden',
  },
  faqShellDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  supportVisual: {
    flex: 0.78,
    minHeight: 320,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supportCard: {
    width: 250,
    height: 250,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(122, 60, 255, 0.42)',
    backgroundColor: 'rgba(122, 60, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  supportBubble: {
    position: 'absolute',
    right: 48,
    top: 54,
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: neonPalette.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  faqContent: {
    flex: 1.2,
    gap: 20,
  },
  faqList: {
    gap: 10,
  },
  faqItem: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neonPalette.line,
    backgroundColor: 'rgba(245, 247, 255, 0.045)',
    padding: 16,
    gap: 10,
    overflow: 'hidden',
  },
  faqItemOpen: {
    borderColor: 'rgba(0, 194, 255, 0.45)',
    backgroundColor: 'rgba(0, 194, 255, 0.07)',
  },
  faqItemHover: {
    borderColor: 'rgba(0, 194, 255, 0.36)',
    transform: [{ translateY: -2 }],
  },
  faqQuestionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'center',
  },
  faqQuestion: {
    color: neonPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 14.5,
    lineHeight: 21,
    fontWeight: '900',
  },
  faqAnswerWrap: {
    overflow: 'hidden',
  },
  faqAnswer: {
    color: 'rgba(207, 218, 235, 0.82)',
    fontFamily: Typography.body,
    fontSize: 13.5,
    lineHeight: 21,
    paddingTop: 2,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 45, 122, 0.34)',
    backgroundColor: 'rgba(5, 8, 22, 0.96)',
    paddingHorizontal: 22,
    paddingTop: 34,
    paddingBottom: 18,
  },
  footerInner: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 28,
    justifyContent: 'space-between',
  },
  footerBrand: {
    width: 260,
    gap: 14,
  },
  footerDescription: {
    color: neonPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12.5,
    lineHeight: 19,
  },
  footerColumns: {
    flex: 1,
    minWidth: 360,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 26,
    justifyContent: 'space-between',
  },
  footerColumn: {
    minWidth: 120,
    gap: 9,
  },
  footerColumnTitle: {
    color: neonPalette.text,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  footerLinkButton: {
    minHeight: 24,
    justifyContent: 'center',
  },
  footerLink: {
    color: neonPalette.mutedStrong,
    fontFamily: Typography.body,
    fontSize: 12,
  },
  contactCard: {
    minWidth: 230,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neonPalette.line,
    backgroundColor: 'rgba(245, 247, 255, 0.045)',
    padding: 18,
    gap: 10,
  },
  contactTitle: {
    color: neonPalette.text,
    fontFamily: Typography.display,
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 4,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  contactText: {
    color: neonPalette.mutedStrong,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
  },
  footerBottom: {
    width: '100%',
    maxWidth: 1240,
    alignSelf: 'center',
    borderTopWidth: 1,
    borderTopColor: 'rgba(245, 247, 255, 0.08)',
    marginTop: 28,
    paddingTop: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 10,
  },
  footerBottomText: {
    color: 'rgba(138, 147, 178, 0.78)',
    fontFamily: Typography.body,
    fontSize: 11,
  },
  buttonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.985 }],
  },
  hoverLift: {
    transform: [{ translateY: -2 }, { scale: 1.02 }],
  },
});
