import { StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import { portalGlass, portalPalette } from '../portal-theme';

export const styles = StyleSheet.create({
  skeletonHero: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 24,
    justifyContent: 'space-between',
  },
  skeletonHeroLeft: {
    flex: 1,
    flexBasis: 300,
    gap: 14,
    minWidth: 0,
  },
  skeletonPhone: {
    alignItems: 'center',
    flexShrink: 0,
  },
  errorState: {
    alignItems: 'center',
    gap: 12,
  },
  retryButton: {
    alignItems: 'center',
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 18,
  },
  retryButtonText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  heroCard: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    minWidth: 0,
    overflow: 'hidden',
    padding: AppTheme.spacing.lg,
    ...portalGlass(),
  },
  heroBody: {
    flexDirection: 'row',
    gap: 32,
    justifyContent: 'space-between',
  },
  heroBodyCompact: {
    flexDirection: 'column',
    gap: 24,
  },
  heroLeft: {
    flex: 1,
    flexBasis: 340,
    gap: 10,
    justifyContent: 'center',
    minWidth: 0,
  },
  heroTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 38,
  },
  heroDesc: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 420,
  },
  heroBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  heroBadgeAvailable: {
    alignItems: 'center',
    backgroundColor: portalPalette.successSoft,
    borderRadius: AppTheme.radius.pill,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  heroBadgeText: {
    color: portalPalette.success,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  heroVersionBadge: {
    color: portalPalette.mutedSoft,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '700',
  },
  heroActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  dlButton: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 48,
    minWidth: 180,
    paddingHorizontal: 22,
  },
  dlButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '900',
  },
  novidadesButton: {
    alignItems: 'center',
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  novidadesButtonText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  phoneFrame: {
    alignItems: 'center',
    backgroundColor: '#1A1A1A',
    borderRadius: 28,
    flexShrink: 0,
    height: 280,
    justifyContent: 'center',
    padding: 6,
    width: 148,
  },
  phoneNotch: {
    backgroundColor: '#1A1A1A',
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    height: 20,
    position: 'absolute',
    top: 6,
    width: 80,
    zIndex: 2,
  },
  phoneScreen: {
    backgroundColor: '#121821',
    borderRadius: 22,
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  phoneStatusBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingTop: 10,
  },
  phoneStatusText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '700',
  },
  phoneStatusIcons: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  phoneAppContent: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  phoneAppName: {
    color: '#FFFFFF',
    fontFamily: Typography.display,
    fontSize: 14,
    fontWeight: '900',
  },
  phoneAppDesc: {
    color: 'rgba(255,255,255,0.5)',
    fontFamily: Typography.body,
    fontSize: 10,
  },
  phoneNavBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    paddingBottom: 10,
  },
  infoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoFactCard: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 160,
    gap: 4,
    minWidth: 0,
    padding: AppTheme.spacing.md,
  },
  infoFactIconWrap: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    marginBottom: 4,
    width: 38,
  },
  infoFactLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
  },
  infoFactValue: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 24,
  },
  downloadCard: {
    alignItems: 'center',
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 28,
    minWidth: 0,
    padding: AppTheme.spacing.lg,
    ...portalGlass(),
  },
  downloadCardCompact: {
    flexDirection: 'column',
    gap: 20,
  },
  qrWrap: {
    alignItems: 'center',
    flexShrink: 0,
    gap: 8,
  },
  qrLoading: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.sm,
    height: 140,
    justifyContent: 'center',
    width: 140,
  },
  qrHint: {
    color: portalPalette.mutedSoft,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  downloadInfoWrap: {
    flex: 1,
    flexBasis: 260,
    gap: 12,
    minWidth: 0,
  },
  downloadTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 20,
    fontWeight: '900',
  },
  downloadSubtitle: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
  },
  downloadMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderRadius: AppTheme.radius.pill,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  metaPillText: {
    color: portalPalette.info,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
  },
  dlButtonLarge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 200,
    paddingHorizontal: 24,
  },
  dlButtonLargeText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 16,
    fontWeight: '900',
  },
  novidadesCard: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    gap: 8,
    minWidth: 0,
    padding: AppTheme.spacing.lg,
    ...portalGlass(),
  },
  novidadesTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 20,
    fontWeight: '900',
  },
  novidadesSubtitle: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 19,
  },
  novidadesList: {
    gap: 8,
    marginTop: 4,
  },
  novidadeItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  novidadeCheckIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.successSoft,
    borderRadius: 12,
    flexShrink: 0,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  novidadeText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 14,
    lineHeight: 20,
    minWidth: 0,
  },
  timelineCard: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    gap: 10,
    minWidth: 0,
    padding: AppTheme.spacing.lg,
    ...portalGlass(),
  },
  timelineTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 20,
    fontWeight: '900',
  },
  timelineSubtitle: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 19,
  },
  timelineList: {
    gap: 0,
    marginTop: 4,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  timelineLine: {
    alignItems: 'center',
    flexShrink: 0,
    width: 24,
  },
  timelineDot: {
    borderRadius: 10,
    height: 10,
    marginTop: 6,
    width: 10,
  },
  timelineDotCurrent: {
    backgroundColor: portalPalette.accent,
  },
  timelineDotPast: {
    backgroundColor: portalPalette.mutedSoft,
  },
  timelineConnector: {
    flex: 1,
    width: 2,
    backgroundColor: portalPalette.line,
    minHeight: 20,
  },
  timelineContent: {
    flex: 1,
    flexBasis: 200,
    gap: 8,
    minWidth: 0,
    paddingBottom: 24,
  },
  timelineContentCompact: {
    paddingBottom: 18,
  },
  timelineHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  timelineVersionWrap: {
    gap: 2,
    minWidth: 0,
  },
  timelineVersion: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 17,
    fontWeight: '900',
  },
  timelineDate: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
  },
  timelineBadgeWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
  },
  expandButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: 8,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  timelineMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  metaPillSmall: {
    color: portalPalette.info,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
  },
  timelineNotes: {
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.sm,
    gap: 6,
    padding: AppTheme.spacing.sm,
  },
  noteRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 7,
  },
  noteText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
  },
  timelineDlButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 16,
  },
  timelineDlButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  tabBar: {
    borderBottomColor: portalPalette.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 0,
    minWidth: 0,
  },
  tabItem: {
    alignItems: 'center',
    borderBottomColor: 'transparent',
    borderBottomWidth: 2,
    flexDirection: 'row',
    gap: 6,
    minHeight: 44,
    paddingHorizontal: 16,
  },
  tabItemActive: {
    borderBottomColor: portalPalette.accent,
  },
  tabText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '800',
  },
  tabTextActive: {
    color: portalPalette.accent,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    gap: 16,
    paddingBottom: 32,
  },
  card: {
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    gap: 12,
    minWidth: 0,
    padding: AppTheme.spacing.lg,
    ...portalGlass(),
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 32,
  },
  emptyTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
  },
  emptyDesc: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    textAlign: 'center',
  },
  sectionTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 18,
    fontWeight: '900',
  },
  sectionSubtitle: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    marginTop: -8,
  },
  sectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    minWidth: 0,
  },
  fieldRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  fieldGroup: {
    flex: 1,
    flexBasis: 200,
    gap: 4,
    minWidth: 0,
  },
  label: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  noteInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  noteInputField: {
    flex: 1,
  },
  addNoteButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.accent,
    borderRadius: AppTheme.radius.sm,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  noteItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  noteEditField: {
    flex: 1,
  },
  removeNoteButton: {
    alignItems: 'center',
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  addVersionButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.accent,
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  addVersionText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  historyVersionCard: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    gap: 10,
    padding: AppTheme.spacing.md,
  },
  historyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  historyIndex: {
    color: portalPalette.mutedSoft,
    fontFamily: Typography.display,
    fontSize: 13,
    fontWeight: '900',
  },
  archivedBadge: {
    backgroundColor: portalPalette.warningSoft,
    borderRadius: AppTheme.radius.pill,
    color: portalPalette.warning,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  currentBadge: {
    backgroundColor: portalPalette.successSoft,
    borderRadius: AppTheme.radius.pill,
    color: portalPalette.success,
    fontFamily: Typography.body,
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  historyActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  historyActionBtn: {
    alignItems: 'center',
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 32,
    paddingHorizontal: 10,
  },
  historyActionBtnActive: {
    backgroundColor: portalPalette.accent,
    borderColor: portalPalette.accent,
  },
  historyActionText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '800',
  },
  historyActionTextActive: {
    color: '#FFFFFF',
  },
  addVersionNoteBtn: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 4,
  },
  addVersionNoteText: {
    color: portalPalette.accent,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
  },
  saveBar: {
    alignItems: 'center',
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
    padding: AppTheme.spacing.md,
    ...portalGlass(),
  },
  dirtyDot: {
    backgroundColor: portalPalette.warning,
    borderRadius: 6,
    height: 10,
    width: 10,
  },
  saveStatus: {
    color: portalPalette.muted,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    minWidth: 0,
  },
  saveButton: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 18,
  },
  saveButtonDisabled: {
    opacity: 0.4,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
  },
  loadingText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  statCell: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 140,
    gap: 2,
    minWidth: 0,
    padding: AppTheme.spacing.md,
  },
  statValue: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
  },
  statLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '700',
  },
});
