import { StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import type { useAppTheme } from '@/src/hooks/use-app-theme';
import { MANECOMB_ROUTE_COLOR } from './checklist.utils';

export function createStyles(
  theme: ReturnType<typeof useAppTheme>['theme'],
  isCompact: boolean,
  isPhone: boolean
) {
  return StyleSheet.create({
    centered: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    centeredText: {
      color: theme.colors.muted,
      fontSize: 14,
    },
    header: {
      paddingTop: 4,
      gap: 8,
    },
    eyebrow: {
      color: theme.colors.accent,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 2,
    },
    title: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 26 : 30,
      fontWeight: '900',
      lineHeight: isPhone ? 32 : 36,
    },
    filterFrame: {
      borderRadius: AppTheme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
    },
    filterScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 6,
      gap: 6,
    },
    filterSegment: {
      flexShrink: 0,
      minHeight: 48,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    filterSegmentActive: {
      borderWidth: 1,
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accentSoft,
    },
    filterSegmentText: {
      color: theme.colors.muted,
      fontSize: 14,
      fontWeight: '900',
    },
    filterSegmentTextActive: {
      color: theme.colors.accent,
    },
    section: {
      gap: 14,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    sectionTitleWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
      fontWeight: '900',
    },
    sectionLink: {
      color: theme.colors.muted,
      fontSize: 13,
      fontWeight: '800',
    },
    recordsList: {
      gap: 12,
    },
    recordCard: {
      borderRadius: AppTheme.radius.sm2,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: 14,
      gap: 12,
    },
    recordMain: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    recordLead: {
      flex: 1,
      // Piso de ancho: la identidad de la unidad nunca puede desaparecer,
      // por muchas pastillas de estado que traiga la fila.
      minWidth: 120,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    recordPills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 6,
      // Techo de ancho: sin el, dos pastillas se quedaban con toda la fila.
      // `flexShrink` deja que bajen a una segunda linea antes que aplastar
      // el nombre de la unidad.
      maxWidth: '52%',
      flexShrink: 1,
    },
    recordIcon: {
      width: 44,
      height: 44,
      borderRadius: AppTheme.radius.xs3,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordTitle: {
      color: theme.colors.text,
      fontSize: 17,
      fontWeight: '900',
    },
    recordDriver: {
      color: theme.colors.muted,
      fontSize: 13,
      lineHeight: 18,
      flexShrink: 1,
    },
    recordTimeline: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.line,
      paddingTop: 10,
    },
    timeBlock: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    timeLabel: {
      color: theme.colors.muted,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0.7,
    },
    timeValue: {
      color: theme.colors.text,
      fontFamily: Typography.mono,
      fontSize: 13,
      fontWeight: '900',
    },
    recordActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    miniAction: {
      minHeight: 36,
      borderRadius: AppTheme.radius.xs2,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    miniActionText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(7, 11, 19, 0.34)',
      justifyContent: 'flex-end',
    },
    modalCard: {
      maxHeight: '96%',
      borderTopLeftRadius: AppTheme.radius.lg,
      borderTopRightRadius: AppTheme.radius.lg,
      backgroundColor: theme.colors.background,
      paddingHorizontal: isPhone ? 14 : 18,
      paddingTop: 0,
      paddingBottom: 10,
      gap: 10,
    },
    modalDragArea: {
      minHeight: 28,
      paddingTop: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalDragHandle: {
      width: 40,
      height: 4,
      borderRadius: 999,
      backgroundColor: theme.colors.line,
      alignSelf: 'center',
      marginBottom: 12,
    },
    modalKeyboard: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingBottom: 4,
    },
    modalHeaderCopy: {
      flex: 1,
      minWidth: 0,
    },
    modalTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 21,
      fontWeight: '900',
      flexShrink: 1,
    },
    modalSubtitle: {
      color: theme.colors.muted,
      fontSize: 13,
      lineHeight: 18,
      flexShrink: 1,
    },
    modalClose: {
      width: 42,
      height: 42,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalScroll: {
      // flexGrow:0 mantiene el "abrazar contenido" cuando es corto; flexShrink:1 (el default
      // de RN es 0) deja que el ScrollView ceda ante el maxHeight:'96%' del modalCard y
      // scrollee cuando el contenido excede, en vez de recortarse por el borde del panel.
      flexGrow: 0,
      flexShrink: 1,
    },
    modalScrollContent: {
      gap: 16,
      paddingBottom: 12,
    },
    routeNameInput: {
      minHeight: 46,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '800',
      paddingHorizontal: 12,
    },
    routePreview: {
      height: isPhone ? 150 : 210,
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: theme.mode === 'light' ? '#F2F6FB' : '#101A27',
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    miniMapMarker: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: MANECOMB_ROUTE_COLOR,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    recordCopy: {
      flex: 1,
      minWidth: 0,
    },
    miniMapMarkerShell: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.mode === 'light' ? 'rgba(255,255,255,0.92)' : 'rgba(15,23,42,0.92)',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.18,
      shadowRadius: 6,
      elevation: 4,
    },
    miniMapMarkerShellOrigin: {
      backgroundColor: theme.mode === 'light' ? 'rgba(16,185,129,0.14)' : 'rgba(16,185,129,0.24)',
    },
    miniMapMarkerShellDestination: {
      backgroundColor: theme.mode === 'light' ? 'rgba(227,30,36,0.14)' : 'rgba(227,30,36,0.24)',
    },
    miniMapMarkerOrigin: {
      backgroundColor: theme.colors.success,
    },
    miniMapMarkerDestination: {
      width: 32,
      height: 32,
      borderRadius: AppTheme.radius.sm,
      backgroundColor: MANECOMB_ROUTE_COLOR,
    },
    miniMapMarkerText: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '900',
      lineHeight: 14,
      textAlign: 'center',
    },
    miniMapVehicleWrap: {
      width: 54,
      height: 54,
      alignItems: 'center',
      justifyContent: 'center',
    },
    miniMapAccuracyHalo: {
      position: 'absolute',
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: theme.mode === 'light' ? 'rgba(37,99,235,0.14)' : 'rgba(96,165,250,0.20)',
      borderWidth: 1,
      borderColor: theme.mode === 'light' ? 'rgba(37,99,235,0.18)' : 'rgba(147,197,253,0.24)',
    },
    miniMapVehicleMarker: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: theme.colors.info,
      borderWidth: 3,
      borderColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.22,
      shadowRadius: 7,
      elevation: 5,
    },
    miniMapVehicleHeading: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    routePreviewEmpty: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 2,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
      gap: 6,
      backgroundColor: theme.mode === 'light' ? 'rgba(242,246,251,0.82)' : 'rgba(16,26,39,0.82)',
    },
    routePreviewEmptyTitle: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
    },
    routePreviewEmptyText: {
      color: theme.colors.muted,
      fontSize: 12,
      lineHeight: 17,
      textAlign: 'center',
    },
    routeSummary: {
      flexDirection: 'row',
      gap: 10,
    },
    routeSummaryItem: {
      flex: 1,
      borderRadius: AppTheme.radius.sm,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: 12,
      gap: 6,
    },
    summaryLabel: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '800',
    },
    summaryValue: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '900',
      flexShrink: 1,
    },
    progressCard: {
      borderRadius: AppTheme.radius.sm2,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: 14,
      gap: 10,
    },
    progressTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    progressTitle: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: '900',
    },
    progressValue: {
      color: theme.colors.info,
      fontSize: 13,
      fontWeight: '900',
    },
    progressTrack: {
      height: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.line,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: theme.colors.info,
    },
    routeAlert: {
      minHeight: 42,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      borderColor: theme.colors.danger,
      backgroundColor: theme.colors.dangerSoft,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    routeAlertText: {
      flex: 1,
      color: theme.colors.danger,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 17,
    },
    configCard: {
      borderRadius: AppTheme.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: 16,
      gap: 14,
    },
    configTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    configTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 18,
      fontWeight: '900',
    },
    fieldGroup: {
      gap: 8,
    },
    fieldLabel: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    routeEndpoints: {
      gap: 9,
    },
    savedRoutesList: {
      gap: 10,
    },
    savedRouteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    savedRouteButton: {
      flex: 1,
      minHeight: 42,
      borderRadius: AppTheme.radius.xs3,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
    },
    savedRouteDelete: {
      width: 42,
      height: 42,
      borderRadius: AppTheme.radius.xs3,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.danger,
      backgroundColor: theme.colors.dangerSoft,
    },
    savedRouteEdit: {
      width: 42,
      height: 42,
      borderRadius: AppTheme.radius.xs3,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
    },
    savedRouteName: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: '900',
    },
    savedRouteButtonAssigned: {
      opacity: 0.7,
      borderColor: theme.colors.success,
    },
    savedRouteNameAssigned: {
      color: theme.colors.success,
    },
    endpointText: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 20,
    },
    routeActionRow: {
      flexDirection: 'row',
      gap: 10,
    },
    secondaryWide: {
      flex: 1,
      minHeight: 48,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 12,
    },
    secondaryWideText: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    stopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    stopNumber: {
      width: 28,
      height: 28,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.info,
    },
    stopNumberDestination: {
      backgroundColor: theme.colors.accent,
    },
    waypointNumber: {
      width: 28,
      height: 28,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.warning,
    },
    stopNumberText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontWeight: '900',
    },
    stopCopy: {
      flex: 1,
      minWidth: 0,
    },
    stopRemoveButton: {
      width: 32,
      height: 32,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.dangerSoft,
    },
    stopMoveGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    stopMoveButton: {
      width: 28,
      height: 28,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    stopMoveButtonDisabled: {
      opacity: 0.36,
    },
    compactStopsList: {
      gap: 10,
      borderTopWidth: 1,
      borderTopColor: theme.colors.line,
      paddingTop: 10,
    },
    stopTitle: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    stopMeta: {
      color: theme.colors.muted,
      fontSize: 12,
      lineHeight: 17,
    },
    messageText: {
      color: theme.colors.muted,
      fontSize: 12,
      lineHeight: 18,
    },
    unitRouteCard: {
      minHeight: 54,
      borderRadius: AppTheme.radius.sm,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    primaryWide: {
      flex: 1,
      minHeight: 48,
      borderRadius: 15,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    primaryWideInline: {
      flex: 1,
      minHeight: 48,
      borderRadius: 15,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
    },
    primaryWideText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '900',
      flexShrink: 1,
      textAlign: 'center',
    },
    historyErrorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 8,
      paddingHorizontal: 12,
      marginBottom: 8,
      backgroundColor: theme.colors.warning + '1A',
      borderRadius: 8,
    },
    historyErrorText: {
      flex: 1,
      fontSize: 13,
      color: theme.colors.text,
    },
    historyRetryText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.accent,
    },
  });
}
