import type { RadioOperationalPhase, RadioPageIndex } from './types';

export const MIN_RADIO_NOTE_SECONDS = 1;
export const MAX_RADIO_NOTE_SECONDS = 60;
export const INITIAL_RADIO_PAGE_INDEX: RadioPageIndex = 1;
export const RADIO_PAGES = ['Canales', 'Radio', 'Audios'] as const;

export const RADIO_PHASE_TRANSITIONS: Record<RadioOperationalPhase, RadioOperationalPhase[]> = {
  IDLE: ['CONNECTING', 'READY', 'TRANSMITTING', 'RECEIVING', 'OFFLINE', 'ERROR'],
  CONNECTING: ['READY', 'RECONNECTING', 'UNAUTHORIZED', 'OFFLINE', 'ERROR'],
  RECONNECTING: ['READY', 'UNAUTHORIZED', 'OFFLINE', 'ERROR'],
  READY: ['TRANSMITTING', 'RECEIVING', 'CHANNEL_BUSY', 'OFFLINE', 'RECONNECTING', 'ERROR'],
  TRANSMITTING: ['READY', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  RECEIVING: ['READY', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  CHANNEL_BUSY: ['READY', 'RECEIVING', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  UNAUTHORIZED: ['CONNECTING', 'OFFLINE'],
  RECORDING: ['UPLOADING', 'READY', 'ERROR', 'OFFLINE'],
  UPLOADING: ['READY', 'ERROR', 'OFFLINE'],
  LOADING: ['BUFFERING', 'PLAYING', 'PAUSED', 'FINISHED', 'ERROR', 'READY', 'OFFLINE'],
  BUFFERING: ['PLAYING', 'PAUSED', 'FINISHED', 'ERROR', 'READY', 'OFFLINE'],
  PLAYING: ['BUFFERING', 'PAUSED', 'FINISHED', 'ERROR', 'READY', 'OFFLINE'],
  PAUSED: ['PLAYING', 'READY', 'ERROR', 'OFFLINE'],
  FINISHED: ['READY', 'LOADING', 'OFFLINE'],
  ERROR: ['READY', 'RECORDING', 'LOADING', 'OFFLINE'],
  OFFLINE: ['CONNECTING', 'READY', 'ERROR'],
};
