import type { RadioOperationalPhase, RadioPageIndex } from './types';

export const MIN_RADIO_NOTE_SECONDS = 1;
export const MAX_RADIO_NOTE_SECONDS = 60;
export const INITIAL_RADIO_PAGE_INDEX: RadioPageIndex = 1;
export const RADIO_PAGES = ['Canales', 'Radio', 'Audios'] as const;

export const RADIO_PHASE_TRANSITIONS: Record<RadioOperationalPhase, RadioOperationalPhase[]> = {
  IDLE: ['CONNECTING', 'OFFLINE', 'ERROR'],
  CONNECTING: ['JOIN_SENT', 'RECONNECTING', 'UNAUTHORIZED', 'OFFLINE', 'ERROR'],
  JOIN_SENT: ['READY', 'RECONNECTING', 'UNAUTHORIZED', 'OFFLINE', 'ERROR'],
  RECONNECTING: ['JOIN_SENT', 'UNAUTHORIZED', 'OFFLINE', 'ERROR'],
  READY: ['CONNECTING', 'REQUESTING', 'RECEIVING', 'CHANNEL_BUSY', 'OFFLINE', 'RECONNECTING', 'ERROR'],
  REQUESTING: ['TRANSMITTING', 'CHANNEL_BUSY', 'UNAUTHORIZED', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  TRANSMITTING: ['READY', 'UPLOADING', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  RECEIVING: ['READY', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  CHANNEL_BUSY: ['READY', 'RECEIVING', 'RECONNECTING', 'OFFLINE', 'ERROR'],
  UNAUTHORIZED: ['CONNECTING', 'OFFLINE'],
  UPLOADING: ['READY', 'RECONNECTING', 'ERROR', 'OFFLINE'],
  ERROR: ['CONNECTING', 'RECONNECTING', 'READY', 'OFFLINE'],
  OFFLINE: ['CONNECTING', 'RECONNECTING', 'ERROR'],
};
