import { AppTheme, Typography } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';
import type { useAppTheme } from '@/src/hooks/use-app-theme';

export function createStyles(
  theme: ReturnType<typeof useAppTheme>['theme'],
  isDesktop: boolean,
  isPhone: boolean
) {
  return StyleSheet.create({
    container: {
      flex: 1,
      minHeight: 0,
      gap: 10,
      backgroundColor: theme.colors.background,
    },
    pagerShell: {
      flex: 1,
      minHeight: 0,
      width: '100%',
    },
    pager: {
      flex: 1,
    },
    page: {
      flex: 1,
      minHeight: 0,
      paddingRight: isPhone ? 0 : 2,
    },
    radioPage: {
      justifyContent: 'space-between',
    },
    pageIndicators: {
      minHeight: 22,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingTop: 4,
    },
    pageIndicatorHit: {
      minWidth: 22,
      minHeight: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pageIndicator: {
      width: 7,
      height: 7,
      borderRadius: 999,
      backgroundColor: theme.colors.line,
      opacity: 0.72,
    },
    pageIndicatorActive: {
      width: 22,
      backgroundColor: theme.colors.accent,
      opacity: 1,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 16,
      paddingTop: 8,
    },
    headerCopy: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    title: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 25 : 30,
      lineHeight: isPhone ? 30 : 36,
    },
    headerPills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 8,
      marginTop: 8,
    },
    headerMiniChip: {
      minHeight: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 9,
    },
    headerMiniText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    headerControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flexShrink: 0,
    },
    deviceCompactBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      maxWidth: isPhone ? 180 : 340,
    },
    deviceCompactChip: {
      minHeight: 40,
      maxWidth: isPhone ? 82 : 152,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 10,
    },
    deviceCompactText: {
      flex: 1,
      minWidth: 0,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
    },
    iconButton: {
      width: 48,
      height: 48,
      borderRadius: AppTheme.radius.md,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsPanel: {
      alignSelf: 'stretch',
      width: '100%',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: isPhone ? 12 : 14,
      gap: 12,
      marginBottom: 0,
    },
    settingItem: {
      gap: 8,
    },
    settingLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    settingLabel: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '800',
    },
    audioStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    audioStatusDot: {
      width: 9,
      height: 9,
      borderRadius: 999,
    },
    deviceList: {
      flexDirection: 'row',
    },
    deviceChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.line,
      marginRight: 8,
    },
    deviceChipActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    deviceChipText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
    },
    deviceChipTextActive: {
      color: '#FFFFFF',
      fontWeight: '700',
    },
    refreshButton: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accentSoft,
      width: 34,
      height: 34,
      borderRadius: 12,
    },
    directoryPanel: {
      flex: 1,
      width: '100%',
      minWidth: 0,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: isPhone ? 14 : 16,
      gap: 12,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 10px 20px rgba(4, 16, 27, 0.08)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.08,
            shadowRadius: 16,
            shadowOffset: { width: 0, height: 8 },
            elevation: 4,
          }),
      maxHeight: undefined,
    },
    searchShell: {
      minHeight: 52,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
    },
    searchInput: {
      flex: 1,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 15,
    },
    quickActionCard: {
      minHeight: 56,
      borderRadius: 18,
      backgroundColor: theme.colors.accent,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    quickActionLead: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    quickActionTitle: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '800',
    },
    directoryScroll: {
      flex: 1,
      minHeight: 0,
    },
    directoryContent: {
      gap: 14,
      paddingBottom: 8,
    },
    sectionBlock: {
      gap: 10,
    },
    sectionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
      lineHeight: 26,
    },
    channelCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 10,
      gap: 0,
    },
    channelCardActive: {
      backgroundColor: theme.colors.accentSoft,
      borderColor: theme.colors.accent,
    },
    listCardHover: {
      transform: [{ translateY: -1 }],
      ...(Platform.OS === 'web'
        ? {
            boxShadow: `0px 10px 24px ${theme.colors.shadow}`,
          }
        : {
            elevation: 5,
          }),
    },
    channelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    channelAvatar: {
      width: 38,
      height: 38,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    channelCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    channelTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '800',
    },
    channelMeta: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
    },
    channelStatusDot: {
      width: 9,
      height: 9,
      borderRadius: 999,
      backgroundColor: theme.colors.success,
    },
    channelActionIcon: {
      width: 32,
      height: 32,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    unreadBubble: {
      minWidth: 26,
      height: 26,
      paddingHorizontal: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    unreadBubbleText: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
    },
    contactRow: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    contactLead: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    contactCopy: {
      flex: 1,
      minWidth: 0,
      gap: 0,
    },
    contactTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '800',
    },
    contactActionButton: {
      width: 40,
      height: 40,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.accent,
      borderWidth: 1,
      borderColor: theme.colors.accent,
    },
    heroCard: {
      flex: 1,
      minWidth: 0,
      borderRadius: AppTheme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      justifyContent: 'space-between',
      padding: isPhone ? 12 : 16,
      gap: isPhone ? 8 : 10,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 16px 34px rgba(4, 16, 27, 0.12)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.12,
            shadowRadius: 20,
            shadowOffset: { width: 0, height: 10 },
            elevation: 6,
          }),
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    heroCopy: {
      flex: 1,
      width: '100%',
      minWidth: 0,
      gap: 6,
    },
    heroEyebrow: {
      color: theme.colors.accent,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 24 : 30,
      lineHeight: isPhone ? 30 : 36,
    },
    heroPills: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
    },
    operationalBanner: {
      minHeight: 58,
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    operationalIcon: {
      width: 38,
      height: 38,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    operationalCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    operationalTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '900',
    },
    operationalAction: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
    },
    heroDeviceBar: {
      width: '100%',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      gap: 8,
    },
    pttCenter: {
      flexGrow: 0,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: isPhone ? 232 : 266,
    },
    pttHalo: {
      position: 'absolute',
      width: isPhone ? 220 : 256,
      height: isPhone ? 220 : 256,
      borderRadius: 999,
      backgroundColor: theme.colors.accentSoft,
    },
    pttOuter: {
      width: isPhone ? 220 : 256,
      height: isPhone ? 220 : 256,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.02)',
      padding: 12,
    },
    pttButton: {
      width: '100%',
      height: '100%',
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 16,
    },
    pttButtonIdle: {
      backgroundColor: theme.colors.accent,
      opacity: 0.92,
    },
    pttButtonUploading: {
      backgroundColor: theme.colors.info,
    },
    pttButtonBusy: {
      backgroundColor: theme.colors.warning,
    },
    pttButtonError: {
      backgroundColor: theme.colors.danger,
    },
    pttButtonOffline: {
      backgroundColor: theme.colors.muted,
    },
    pttButtonRecording: {
      backgroundColor: theme.colors.danger,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: `0px 0px 32px ${theme.colors.dangerSoft}`,
          }
        : {
            elevation: 10,
          }),
    },
    pttButtonDisabled: {
      opacity: 0.45,
    },
    pttButtonTitle: {
      color: '#FFFFFF',
      fontFamily: Typography.display,
      fontSize: isPhone ? 24 : 27,
      fontWeight: '900',
    },
    pttButtonSubtitle: {
      color: 'rgba(255,255,255,0.78)',
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '700',
      textAlign: 'center',
    },
    consoleMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minWidth: 0,
      gap: 12,
      paddingVertical: 2,
    },
    consoleMetaItem: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    consoleMetaCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    consoleMetaLabel: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '700',
    },
    consoleMetaValue: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 13,
      lineHeight: 16,
    },
    consoleMetaDivider: {
      width: 1,
      height: 28,
      backgroundColor: theme.colors.line,
    },
    historyPanel: {
      flex: 1,
      minHeight: 0,
      minWidth: 0,
      borderRadius: isDesktop ? 28 : 30,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: isPhone ? 14 : 18,
      gap: 12,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 10px 20px rgba(4, 16, 27, 0.08)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.08,
            shadowRadius: 16,
            shadowOffset: { width: 0, height: 8 },
            elevation: 4,
          }),
    },
    historyContent: {
      gap: 10,
      paddingBottom: 16,
    },
    audioPageHeader: {
      gap: 10,
    },
    filterRow: {
      gap: 8,
      paddingRight: 4,
    },
    filterChip: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    filterChipActive: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accentSoft,
    },
    filterChipText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
    },
    filterChipTextActive: {
      color: theme.colors.accent,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      paddingVertical: 44,
      paddingHorizontal: 18,
    },
    emptyIconShell: {
      width: 64,
      height: 64,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyTitle: {
      color: theme.colors.muted,
      fontFamily: Typography.display,
      fontSize: 18,
      textAlign: 'center',
    },
    emptyText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 14,
      lineHeight: 22,
      textAlign: 'center',
      maxWidth: 340,
    },
  });
}
