import { StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import type { useAppTheme } from '@/src/hooks/use-app-theme';

/**
 * Estilos del Directorio. Viven fuera de la pantalla para que los componentes
 * extraidos puedan compartirlos sin importar la pantalla y crear un ciclo.
 */
export type DirectoryStyles = ReturnType<typeof createDirectoryStyles>;

export function createDirectoryStyles(theme: ReturnType<typeof useAppTheme>['theme'], isPhone = false) {
  return StyleSheet.create({
    header: { gap: 8, maxWidth: 760, paddingTop: isPhone ? AppTheme.spacing.sm : AppTheme.spacing.md },
    title: { color: theme.colors.text, fontFamily: Typography.display, fontSize: isPhone ? 24 : 30, fontWeight: '900' },
    subtitle: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: isPhone ? 13 : 14, lineHeight: isPhone ? 20 : 21 },
    tabs: { flexDirection: 'row', gap: 8 },
    tab: { alignItems: 'center', backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, flex: 1, flexDirection: 'row', gap: 8, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 11 },
    tabActive: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.accent },
    tabText: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: 13, fontWeight: '800' },
    tabTextActive: { color: theme.colors.accent },
    messageBox: { backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, padding: 12 },
    messageText: { color: theme.colors.text, fontFamily: Typography.body, fontSize: 13, lineHeight: 19 },
    directoryCard: { width: '100%' },
    sectionHeader: { alignItems: isPhone ? 'stretch' : 'center', flexDirection: isPhone ? 'column' : 'row', gap: 12, justifyContent: 'space-between' },
    sectionCopy: { flex: 1, gap: 6, minWidth: 0 },
    sectionTitle: { color: theme.colors.text, fontFamily: Typography.display, fontSize: 20, fontWeight: '900' },
    sectionSubtitle: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: isPhone ? 13 : 14, lineHeight: isPhone ? 20 : 22 },
    usersList: { gap: AppTheme.spacing.md },
    userRow: { backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, gap: isPhone ? 10 : 12, padding: isPhone ? AppTheme.spacing.sm : AppTheme.spacing.md },
    userTop: { alignItems: 'flex-start', flexDirection: isPhone ? 'column' : 'row', gap: 12 },
    userMeta: { flex: 1, gap: 6, minWidth: 0 },
    userName: { color: theme.colors.text, fontFamily: Typography.display, fontSize: isPhone ? 17 : 19, fontWeight: '900' },
    userEmail: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: isPhone ? 13 : 14 },
    pillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    summaryRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    summaryText: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: 12, fontWeight: '700' },
    actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    actionButton: { alignItems: 'center', backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: 12, paddingVertical: 9 },
    actionButtonPressed: { opacity: 0.76, transform: [{ scale: 0.99 }] },
    actionText: { color: theme.colors.text, fontFamily: Typography.body, fontSize: 12, fontWeight: '800' },
    profileDetail: { borderTopColor: theme.colors.line, borderTopWidth: 1, gap: 10, paddingTop: 12 },
    detailsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    detailItem: { backgroundColor: theme.colors.card, borderRadius: AppTheme.radius.md, flex: 1, gap: 6, minWidth: isPhone ? '100%' : 150, padding: AppTheme.spacing.sm },
    detailLabel: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: 12, fontWeight: '800' },
    detailValue: { color: theme.colors.text, fontFamily: Typography.body, fontSize: isPhone ? 13 : 14, fontWeight: '800' },
    profileNote: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: 12, lineHeight: 18 },
    emptyState: { alignItems: 'center', backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, gap: 10, padding: AppTheme.spacing.md },
    primaryButton: { alignItems: 'center', alignSelf: isPhone ? 'stretch' : 'auto', backgroundColor: theme.colors.accent, borderRadius: AppTheme.radius.md, flexDirection: 'row', gap: 7, justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 10 },
    primaryButtonText: { color: '#FFFFFF', fontFamily: Typography.body, fontSize: 13, fontWeight: '900' },
    secondaryButton: { alignItems: 'center', backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, justifyContent: 'center', minHeight: 40, paddingHorizontal: 14, paddingVertical: 9 },
    secondaryButtonText: { color: theme.colors.text, fontFamily: Typography.body, fontSize: 13, fontWeight: '800' },
    dangerButton: { backgroundColor: theme.colors.danger },
    disabledButton: { opacity: 0.45 },
    dangerText: { color: theme.colors.danger, fontFamily: Typography.body, fontSize: 12, fontWeight: '800', lineHeight: 18 },
    vehicleHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
    vehicleIcon: { alignItems: 'center', backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: 18, borderWidth: 1, height: 56, justifyContent: 'center', width: 56 },
    overlay: { alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.72)', flex: 1, justifyContent: 'center', padding: 18 },
    modal: { backgroundColor: theme.colors.surface, borderColor: theme.colors.line, borderRadius: AppTheme.radius.lg, borderWidth: 1, gap: 12, maxHeight: '90%', maxWidth: 560, padding: isPhone ? 16 : 20, width: '100%' },
    modalLarge: { backgroundColor: theme.colors.surface, borderColor: theme.colors.line, borderRadius: AppTheme.radius.lg, borderWidth: 1, maxHeight: '86%', maxWidth: 680, padding: isPhone ? 16 : 20, width: '100%' },
    modalHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
    modalTitle: { color: theme.colors.text, fontFamily: Typography.display, fontSize: 20, fontWeight: '900' },
    modalActions: { flexDirection: isPhone ? 'column-reverse' : 'row', gap: 10, justifyContent: 'flex-end' },
    modalScroll: { gap: 10, paddingTop: 14 },
    iconButton: { alignItems: 'center', backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: 20, borderWidth: 1, height: 40, justifyContent: 'center', width: 40 },
    documentRow: { backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, gap: 10, padding: 12 },
    documentTitle: { color: theme.colors.text, fontFamily: Typography.body, fontSize: 14, fontWeight: '900' },
    impactBox: { backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, gap: 7, padding: 12 },
    impactErrorBox: { backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.danger, borderRadius: AppTheme.radius.md, borderWidth: 1, gap: 10, padding: 12 },
    loadingRow: { alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 40 },
    inputLabel: { color: theme.colors.text, fontFamily: Typography.body, fontSize: 12, fontWeight: '800' },
    input: { backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, color: theme.colors.text, fontFamily: Typography.body, fontSize: 14, minHeight: 46, paddingHorizontal: 12, paddingVertical: 10 },
    textArea: { minHeight: 82, textAlignVertical: 'top' },
    segmentRow: { flexDirection: 'row', gap: 8 },
    segment: { alignItems: 'center', backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, flex: 1, padding: 10 },
    segmentActive: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.accent },
    segmentText: { color: theme.colors.muted, fontFamily: Typography.body, fontSize: 12, fontWeight: '800' },
    segmentTextActive: { color: theme.colors.accent },
    driverChoice: { alignItems: 'center', backgroundColor: theme.colors.surfaceAlt, borderColor: theme.colors.line, borderRadius: AppTheme.radius.md, borderWidth: 1, flexDirection: 'row', gap: 10, padding: 12 },
    dangerChoice: { borderColor: theme.colors.danger },
    selectedChoice: { backgroundColor: theme.colors.accentSoft, borderColor: theme.colors.accent },
  });
}
