import { Platform, StyleSheet } from 'react-native';
import { Typography } from '@/constants/theme';
import { palette } from './checkout.constants';

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: palette.background,
    flex: 1,
    minHeight: '100vh' as any,
  },
  scroll: {
    flex: 1,
  },
  content: {
    gap: 18,
    marginHorizontal: 'auto' as any,
    maxWidth: 1320,
    minHeight: '100vh' as any,
    padding: 24,
    width: '100%',
  },
  contentPhone: {
    padding: 14,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  backgroundGlowTop: {
    backgroundColor: 'rgba(168, 85, 247, 0.2)',
    borderRadius: 260,
    height: 520,
    position: 'absolute',
    right: -170,
    top: -210,
    width: 520,
  },
  backgroundGlowBottom: {
    backgroundColor: 'rgba(255, 36, 92, 0.16)',
    borderRadius: 280,
    bottom: -210,
    height: 560,
    left: -220,
    position: 'absolute',
    width: 560,
  },
  backgroundRail: {
    backgroundColor: 'rgba(35, 213, 255, 0.08)',
    height: 1,
    left: -120,
    position: 'absolute',
    right: -120,
    top: 160,
    transform: [{ rotate: '-5deg' }],
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderColor: palette.line,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 14,
  },
  backText: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  checkoutFrame: {
    borderColor: 'rgba(168, 85, 247, 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 24,
    overflow: 'hidden',
    padding: 24,
    ...(Platform.OS === 'web'
      ? ({
          backgroundImage: 'linear-gradient(145deg, rgba(5, 8, 22, 0.94), rgba(10, 16, 36, 0.96))',
          boxShadow: '0 0 0 1px rgba(168, 85, 247, 0.08), 0 28px 90px rgba(0, 0, 0, 0.46)',
        } as any)
      : {
          backgroundColor: 'rgba(7, 12, 28, 0.96)',
        }),
  },
  stepper: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    minHeight: 48,
  },
  stepItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  stepBadge: {
    alignItems: 'center',
    borderColor: palette.line,
    borderRadius: 22,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  stepBadgeActive: {
    backgroundColor: 'rgba(168, 85, 247, 0.22)',
    borderColor: palette.violet,
  },
  stepNumber: {
    color: palette.mutedSoft,
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '900',
  },
  stepNumberActive: {
    color: palette.text,
  },
  stepLabel: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '800',
  },
  stepLabelActive: {
    color: palette.violet,
  },
  stepLine: {
    backgroundColor: 'rgba(168, 85, 247, 0.28)',
    height: 1,
    width: 82,
  },
  checkoutGrid: {
    gap: 24,
  },
  checkoutGridWide: {
    alignItems: 'stretch',
    flexDirection: 'row',
  },
  leftPanel: {
    borderColor: palette.lineStrong,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1.55,
    gap: 20,
    minWidth: 0,
    padding: 24,
    ...(Platform.OS === 'web'
      ? ({ backgroundImage: 'linear-gradient(145deg, rgba(16, 20, 44, 0.94), rgba(32, 18, 54, 0.74))' } as any)
      : { backgroundColor: palette.panel }),
  },
  fullPanel: {
    width: '100%',
  },
  panelTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  panelTitleIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(168, 85, 247, 0.14)',
    borderRadius: 10,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  panelTitleCopy: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  panelTitle: {
    color: palette.text,
    fontFamily: Typography.display,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
  },
  panelSubtitle: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
  },
  methodTabs: {
    borderColor: palette.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    overflow: 'hidden',
  },
  methodTab: {
    alignItems: 'center',
    borderColor: palette.line,
    borderRightWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 64,
    minWidth: 220,
    paddingHorizontal: 14,
  },
  methodTabActive: {
    backgroundColor: 'rgba(168, 85, 247, 0.22)',
  },
  methodLabel: {
    color: palette.text,
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
    minWidth: 0,
  },
  methodLabelActive: {
    color: '#FFFFFF',
  },
  formGrid: {
    gap: 16,
  },
  testPaymentPanel: {
    borderColor: 'rgba(82, 242, 167, 0.35)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 18,
    padding: 18,
    ...(Platform.OS === 'web'
      ? ({ backgroundImage: 'linear-gradient(145deg, rgba(6, 32, 28, 0.82), rgba(16, 20, 44, 0.9))' } as any)
      : { backgroundColor: 'rgba(6, 32, 28, 0.82)' }),
  },
  testModeHeader: {
    gap: 8,
  },
  testModeBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(82, 242, 167, 0.12)',
    borderColor: 'rgba(82, 242, 167, 0.42)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 34,
    paddingHorizontal: 10,
  },
  testModeBadgeText: {
    color: palette.lime,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  testModeText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
  },
  inlineFields: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  field: {
    flex: 1,
    gap: 8,
    minWidth: 220,
  },
  fieldLabel: {
    color: 'rgba(248, 250, 252, 0.82)',
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '800',
  },
  inputShell: {
    alignItems: 'center',
    backgroundColor: 'rgba(5, 8, 22, 0.68)',
    borderColor: palette.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 14,
  },
  input: {
    color: palette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 0,
  },
  speiPanel: {
    alignItems: 'center',
    backgroundColor: 'rgba(35, 213, 255, 0.08)',
    borderColor: 'rgba(35, 213, 255, 0.24)',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 14,
    padding: 18,
  },
  speiCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  speiTitle: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '900',
  },
  speiText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
  },
  securityNote: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: palette.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  addonOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderColor: palette.line,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  addonCopy: {
    flex: 1,
    gap: 2,
  },
  addonTitle: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '800',
  },
  addonText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 17,
  },
  securityText: {
    color: palette.muted,
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
    textAlign: 'center',
  },
  messageBox: {
    backgroundColor: 'rgba(255, 36, 92, 0.14)',
    borderColor: 'rgba(255, 36, 92, 0.46)',
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
  },
  messageText: {
    color: '#FFB4C8',
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'center',
  },
  payButton: {
    alignItems: 'center',
    backgroundColor: palette.accent,
    borderRadius: 10,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    minHeight: 64,
    paddingHorizontal: 18,
    ...(Platform.OS === 'web'
      ? ({
          backgroundImage: 'linear-gradient(135deg, #F3155F, #B72CF5 58%, #7C3AED)',
          boxShadow: '0 18px 42px rgba(255, 36, 92, 0.26), 0 0 24px rgba(168, 85, 247, 0.24)',
          cursor: 'pointer',
        } as any)
      : null),
  },
  payButtonText: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 17,
    fontWeight: '900',
    minWidth: 0,
    textAlign: 'center',
  },
  disabledButton: {
    opacity: 0.58,
  },
  pressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  summaryPanel: {
    borderColor: 'rgba(255, 36, 92, 0.7)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 22,
    minWidth: 300,
    padding: 24,
    ...(Platform.OS === 'web'
      ? ({ backgroundImage: 'linear-gradient(145deg, rgba(11, 14, 34, 0.96), rgba(28, 13, 45, 0.9))' } as any)
      : { backgroundColor: palette.panelStrong }),
  },
  summaryHero: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 18,
    minWidth: 0,
  },
  summaryIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(168, 85, 247, 0.18)',
    borderColor: 'rgba(168, 85, 247, 0.42)',
    borderRadius: 12,
    borderWidth: 1,
    height: 88,
    justifyContent: 'center',
    width: 88,
  },
  summaryCopy: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  summaryPlan: {
    color: palette.text,
    fontFamily: Typography.display,
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
  },
  summaryPrice: {
    color: palette.violet,
    fontFamily: Typography.body,
    fontSize: 16,
    fontWeight: '900',
  },
  summaryMeta: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 20,
  },
  totals: {
    borderBottomColor: palette.line,
    borderBottomWidth: 1,
    borderTopColor: palette.line,
    borderTopWidth: 1,
    gap: 12,
    paddingVertical: 18,
  },
  totalRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  totalLabel: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '700',
  },
  totalLabelStrong: {
    color: palette.text,
    fontWeight: '900',
  },
  totalValue: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '800',
  },
  totalValueStrong: {
    fontFamily: Typography.display,
    fontSize: 24,
    fontWeight: '900',
  },
  totalDivider: {
    backgroundColor: palette.line,
    height: 1,
  },
  summaryBenefits: {
    gap: 10,
  },
  summaryBenefitsTitle: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  summaryBenefitRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  summaryBenefitText: {
    color: palette.muted,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 19,
    minWidth: 0,
  },
  cancelBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: palette.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  cancelCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  cancelTitle: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  cancelText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  trustStrip: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderColor: palette.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: 16,
  },
  trustItem: {
    alignItems: 'center',
    flex: 1,
    flexBasis: 260,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  trustIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  trustCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  trustTitle: {
    color: palette.text,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  trustBody: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
  },
  donePanel: {
    alignItems: 'center',
    borderColor: 'rgba(82, 242, 167, 0.42)',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    minHeight: 420,
    justifyContent: 'center',
    padding: 28,
    ...(Platform.OS === 'web'
      ? ({ backgroundImage: 'linear-gradient(145deg, rgba(8, 30, 28, 0.9), rgba(20, 16, 42, 0.94))' } as any)
      : { backgroundColor: palette.panel }),
  },
  doneIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(82, 242, 167, 0.12)',
    borderRadius: 42,
    height: 84,
    justifyContent: 'center',
    width: 84,
  },
  doneTitle: {
    color: palette.text,
    fontFamily: Typography.display,
    fontSize: 30,
    fontWeight: '900',
    lineHeight: 36,
    textAlign: 'center',
  },
  doneText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 15,
    lineHeight: 23,
    maxWidth: 620,
    textAlign: 'center',
  },
  doneButton: {
    marginTop: 8,
    maxWidth: 440,
    width: '100%',
  },
  loadingScreen: {
    alignItems: 'center',
    backgroundColor: palette.background,
    flex: 1,
    gap: 12,
    justifyContent: 'center',
    minHeight: '100vh' as any,
  },
  loadingText: {
    color: palette.muted,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '800',
  },
});
