import { StyleSheet } from 'react-native';
import { DesignSystem, Typography } from '@/constants/theme';

export function createStyles(theme: any, isCompact: boolean, isPhone: boolean) {
  return StyleSheet.create({
    header: {
      gap: 12,
      paddingTop: 8,
    },
    titleRow: {
      flexDirection: isPhone ? 'column' : 'row',
      justifyContent: 'space-between',
      alignItems: isPhone ? 'flex-start' : 'center',
      gap: 12,
    },
    titleCopy: {
      flex: 1,
      minWidth: 0,
      gap: 5,
      maxWidth: 760,
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 2,
    },
    title: {
      fontSize: isPhone ? 24 : 30,
      fontWeight: '900',
      color: theme.colors.text,
      fontFamily: Typography.display,
    },
    subtitle: {
      color: theme.colors.muted,
      fontSize: 14,
      lineHeight: 20,
    },
    summaryHUD: {
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 13,
      paddingVertical: 9,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.line,
      gap: 2,
    },
    summaryHUDLabel: {
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: theme.colors.muted,
    },
    summaryHUDText: {
      fontSize: 16,
      fontWeight: '900',
      color: theme.colors.danger,
    },
    sosGrid: {
      flexDirection: 'row',
      gap: 10,
    },
    sosBtn: {
      flex: 1,
      minHeight: isPhone ? 46 : 50,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      elevation: 4,
    },
    sosBtnDisabled: {
      opacity: 0.62,
    },
    sosBtnText: {
      color: '#FFF',
      fontWeight: '900',
      fontSize: 14,
    },
    contentLayout: {
      flexDirection: isCompact ? 'column' : 'row',
      gap: 14,
      alignItems: 'stretch',
      width: '100%',
      minWidth: 0,
    },
    formCard: {
      flexGrow: 0,
      flexShrink: 0,
      width: isCompact ? '100%' : '34%',
      minWidth: 0,
      maxWidth: isCompact ? undefined : 420,
      backgroundColor: theme.colors.surface,
      padding: isPhone ? 14 : 16,
      gap: 12,
      borderRadius: 16,
    },
    panelHeader: {
      gap: 4,
    },
    panelTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: theme.colors.text,
      fontFamily: Typography.display,
    },
    panelSubtitle: {
      color: theme.colors.muted,
      fontSize: 13,
      lineHeight: 18,
    },
    fieldGroup: {
      gap: 8,
    },
    fieldLabel: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    input: {
      minHeight: DesignSystem.control.md,
      backgroundColor: theme.colors.input,
      borderRadius: DesignSystem.radius.input,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: theme.colors.text,
      fontSize: 14,
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    textArea: {
      height: 88,
      textAlignVertical: 'top',
    },
    chipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: 11,
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    chipText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.colors.muted,
    },
    timelinePanel: {
      flex: 1,
      width: '100%',
      gap: 10,
      minWidth: 0,
      minHeight: 0,
      padding: isPhone ? 12 : 14,
      borderRadius: 16,
      backgroundColor: theme.colors.surface,
    },
    timelineHeaderRow: {
      flexDirection: isPhone ? 'column' : 'row',
      alignItems: isPhone ? 'flex-start' : 'center',
      justifyContent: 'space-between',
      gap: 10,
      minWidth: 0,
    },
    timelineHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    resultCount: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '800',
    },
    filtersScroll: {
      marginHorizontal: -2,
      flexGrow: 0,
    },
    filtersContent: {
      gap: 7,
      paddingHorizontal: 2,
      paddingVertical: 2,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      minHeight: 34,
      paddingHorizontal: 12,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
    },
    filterChipActive: {
      backgroundColor: theme.colors.infoSoft,
      borderColor: theme.colors.info,
    },
    filterChipText: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '800',
    },
    filterChipTextActive: {
      color: theme.colors.info,
    },
    searchShell: {
      minHeight: 40,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 11,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.input,
    },
    searchInput: {
      flex: 1,
      minWidth: 0,
      paddingVertical: 8,
      color: theme.colors.text,
      fontSize: 13,
    },
    clearSearchButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 11,
      paddingVertical: 9,
      borderRadius: 10,
      borderWidth: 1,
    },
    errorText: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 17,
    },
    timelineScroll: {
      maxHeight: isPhone ? 580 : isCompact ? 660 : 720,
      minHeight: orderedPanelMinHeight(isPhone),
    },
    timelineContainer: {
      gap: 8,
      paddingTop: 2,
      paddingBottom: 4,
    },
    timelineItem: {
      flexDirection: 'row',
      gap: 8,
      minWidth: 0,
    },
    timelineLine: {
      alignItems: 'center',
      alignSelf: 'stretch',
      width: 16,
      position: 'relative',
    },
    timelineDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      zIndex: 2,
      marginTop: 17,
      borderWidth: 2,
      borderColor: theme.colors.surface,
    },
    timelineConnector: {
      position: 'absolute',
      top: 28,
      bottom: -10,
      width: 1,
      backgroundColor: theme.colors.line,
    },
    incidentCard: {
      flex: 1,
      minWidth: 0,
      backgroundColor: theme.colors.cardSoft,
      borderRadius: 12,
      borderWidth: 1,
      borderLeftWidth: 3,
      borderColor: theme.colors.line,
      paddingHorizontal: 11,
      paddingVertical: 10,
      gap: 7,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      minWidth: 0,
    },
    typeIconShell: {
      width: 30,
      height: 30,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    incidentHeading: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    incidentTitle: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    incidentTime: {
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '700',
    },
    incidentDesc: {
      color: theme.colors.muted,
      fontSize: 12,
      lineHeight: 17,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    cardFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
    },
    incidentMeta: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    incidentMetaText: {
      flex: 1,
      minWidth: 0,
      color: theme.colors.muted,
      fontSize: 11,
      fontWeight: '700',
    },
    resolveButton: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      borderRadius: 9,
      backgroundColor: theme.colors.successSoft,
    },
    resolveLink: {
      color: theme.colors.success,
      fontSize: 11,
      fontWeight: '900',
    },
    mapButton: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      borderRadius: 9,
      backgroundColor: theme.colors.infoSoft,
    },
    mapLink: {
      color: theme.colors.info,
      fontSize: 11,
      fontWeight: '900',
    },
    loadMoreButton: {
      minHeight: 36,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 12,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
    },
    loadMoreText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    stateBox: {
      minHeight: 160,
      borderRadius: 14,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.colors.line,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: 18,
    },
    stateTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '900',
      fontFamily: Typography.display,
      textAlign: 'center',
    },
    stateBody: {
      color: theme.colors.muted,
      fontSize: 12,
      lineHeight: 18,
      textAlign: 'center',
      maxWidth: 420,
    },
  });
}

function orderedPanelMinHeight(isPhone: boolean) {
  return isPhone ? 180 : 220;
}
