import { StyleSheet } from 'react-native';
import { AppTheme, Typography } from '@/constants/theme';
import { portalPalette } from '../portal-theme';

export const styles = StyleSheet.create({
  assistantHero: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceStrong,
    borderColor: 'rgba(240,68,95,.28)',
    borderRadius: 18,
    borderWidth: 1,
    boxShadow: '0 18px 44px rgba(0,0,0,.24), inset 0 1px 0 rgba(255,255,255,.04)' as any,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    minWidth: 0,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  assistantIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.accentSoft,
    borderColor: 'rgba(240,68,95,.22)',
    borderRadius: 14,
    borderWidth: 1,
    flexShrink: 0,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  assistantCopy: {
    flex: 1,
    gap: 3,
    minWidth: 220,
  },
  assistantStep: {
    color: portalPalette.accent,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  assistantTitle: {
    color: portalPalette.text,
    fontFamily: Typography.display,
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 27,
  },
  assistantDescription: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    lineHeight: 18,
  },
  loadingBox: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    gap: 10,
    justifyContent: 'center',
    minHeight: 130,
    padding: AppTheme.spacing.lg,
  },
  loadingText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '700',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    minWidth: 0,
  },
  metricTile: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(148,163,184,.12)',
    borderRadius: 0,
    borderWidth: 0,
    borderRightWidth: 1,
    flex: 1,
    flexBasis: 190,
    gap: 4,
    minHeight: 82,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  metricHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  metricLabel: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  metricValue: {
    color: portalPalette.text,
    flexShrink: 1,
    fontFamily: Typography.display,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 31,
    minWidth: 0,
  },
  metricDetail: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 17,
    minWidth: 0,
  },
  feedbackBox: {
    alignItems: 'center',
    backgroundColor: portalPalette.infoSoft,
    borderColor: 'rgba(35, 213, 255, 0.18)',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  feedbackText: {
    color: portalPalette.text,
    flex: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
    minWidth: 0,
  },
  keyIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.xs,
    flexShrink: 0,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  keyTopLine: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    minWidth: 0,
  },
  keyValue: {
    color: portalPalette.text,
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    minWidth: 0,
  },
  keyMeta: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 17,
  },
  keyActions: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
    minWidth: 150,
  },
  keyActionButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 34,
    minWidth: 38,
    paddingHorizontal: 10,
  },
  keyDangerButton: {
    backgroundColor: portalPalette.dangerSoft,
    borderColor: 'rgba(255, 90, 122, 0.18)',
  },
  keyInfoButton: {
    backgroundColor: portalPalette.infoSoft,
    borderColor: 'rgba(35, 213, 255, 0.18)',
  },
  keyActionText: {
    color: portalPalette.text,
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
    minWidth: 0,
  },
  keyDangerText: {
    color: portalPalette.danger,
  },
  keyInfoText: {
    color: portalPalette.info,
  },
  disabledButton: {
    opacity: 0.55,
  },
  progressTrack: {
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: AppTheme.radius.pill,
    height: 10,
    minWidth: 0,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: portalPalette.success,
    borderRadius: AppTheme.radius.pill,
    height: 10,
  },
  wizardGrid: {
    gap: 0,
    minWidth: 0,
  },
  stepCard: {
    backgroundColor: 'transparent',
    borderBottomColor: portalPalette.line,
    borderBottomWidth: 1,
    borderRadius: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    minHeight: 72,
    minWidth: 0,
    paddingHorizontal: 4,
    paddingVertical: 10,
  },
  stepCardDone: {
    opacity: 0.72,
  },
  stepTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    minWidth: 0,
  },
  stepIndicators: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 8,
  },
  stepNumber: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: 10,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  stepNumberDone: {
    backgroundColor: portalPalette.success,
    borderColor: portalPalette.success,
  },
  stepNumberText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  stepIcon: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderRadius: 10,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  stepCopy: {
    flex: 1,
    flexBasis: 320,
    gap: 4,
    minWidth: 0,
  },
  stepTitle: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 15,
    fontWeight: '900',
    minWidth: 0,
  },
  stepDescription: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
  },
});
