import { StyleSheet } from 'react-native';
import { AppTheme, palette, Typography } from '@/constants/theme';
import { portalPalette } from '../portal-theme';

export const styles = StyleSheet.create({
  assignmentWorkspace: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 560, minWidth: 0 },
  unitsPanel: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: 14, borderWidth: 1, flexBasis: 190, flexGrow: 1, gap: 6, maxWidth: 230, minWidth: 180, padding: 8 },
  catalogPanel: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: 14, borderWidth: 1, flexBasis: 240, flexGrow: 1, gap: 5, maxWidth: 290, minWidth: 220, padding: 8 },
  previewColumn: { flex: 5, flexBasis: 500, gap: 0, minHeight: 550, minWidth: 330 },
  assignedPanel: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: 14, borderWidth: 1, flexBasis: 270, flexGrow: 1, gap: 8, maxWidth: 320, minWidth: 250, padding: 10 },
  panelHeading: { alignItems: 'center', flexDirection: 'row', gap: 7, justifyContent: 'space-between' },
  panelTitle: { color: portalPalette.text, flex: 1, fontFamily: Typography.body, fontSize: 13, fontWeight: '900' },
  panelCount: { backgroundColor: portalPalette.surfaceSoft, borderRadius: 999, color: portalPalette.muted, fontFamily: Typography.mono, fontSize: 10, fontWeight: '900', minWidth: 22, paddingHorizontal: 6, paddingVertical: 3, textAlign: 'center' },
  unitsList: { gap: 7 },
  unitCard: { alignItems: 'center', backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: 11, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 52, padding: 7, transitionDuration: '0.2s', transitionProperty: 'background-color, border-color, box-shadow, transform', ':hover': { backgroundColor: 'rgba(255,255,255,0.075)', borderColor: portalPalette.muted }, ':active': { transform: 'scale(0.98)' } },
  unitCardActive: { backgroundColor: portalPalette.accentSoft, borderColor: portalPalette.accent, shadowColor: portalPalette.accent, shadowOpacity: 0.22, shadowRadius: 16, elevation: 6 },
  unitIcon: { alignItems: 'center', backgroundColor: portalPalette.accentSoft, borderRadius: 8, height: 32, justifyContent: 'center', width: 32 },
  unitIconActive: { backgroundColor: portalPalette.accent },
  unitCode: { color: portalPalette.text, fontFamily: Typography.display, fontSize: 16, fontWeight: '900' },
  unitDriver: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 10, fontWeight: '700' },
  unitStatus: { color: '#34d399', fontFamily: Typography.body, fontSize: 9, fontWeight: '800', marginTop: 2 },
  compactSearch: { backgroundColor: portalPalette.surfaceSoft, borderRadius: 9, borderWidth: 1, fontFamily: Typography.body, fontSize: 11, minHeight: 34, paddingHorizontal: 10 },
  compactFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  catalogList: { gap: 5, maxHeight: 420, overflow: 'auto' },
  compactRouteCard: { alignItems: 'stretch', backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 6, minHeight: 58, overflow: 'hidden', padding: 5, transitionDuration: '0.2s', transitionProperty: 'background-color, border-color, box-shadow, transform', ':hover': { backgroundColor: 'rgba(255,255,255,0.075)', borderColor: portalPalette.muted }, ':active': { transform: 'scale(0.98)' } },
  compactRouteCardActive: { backgroundColor: portalPalette.accentSoft, borderColor: portalPalette.accent, shadowColor: portalPalette.accent, shadowOpacity: 0.2, shadowRadius: 14, elevation: 6 },
  compactRouteInfo: { flex: 1, gap: 5, justifyContent: 'center', minWidth: 90 },
  compactRouteName: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 10, fontWeight: '900' },
  compactMetrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  compactMetric: { backgroundColor: 'rgba(148,163,184,.1)', borderRadius: 5, color: portalPalette.muted, fontFamily: Typography.mono, fontSize: 8, paddingHorizontal: 5, paddingVertical: 3 },
  thumbnailWrap: { flexBasis: 88, justifyContent: 'center', maxWidth: 98, minWidth: 78 },
  previewMapShell: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: 14, borderBottomLeftRadius: 0, borderBottomRightRadius: 0, borderWidth: 1, flex: 1, minHeight: 450, overflow: 'hidden', position: 'relative' },
  mapLabel: { alignItems: 'center', backgroundColor: 'rgba(7,14,29,.86)', borderBottomRightRadius: 9, flexDirection: 'row', gap: 6, left: 0, paddingHorizontal: 10, paddingVertical: 7, position: 'absolute', top: 0, zIndex: 5 },
  mapLabelText: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 10, fontWeight: '800' },
  mapActionBar: { alignItems: 'center', backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderBottomLeftRadius: 14, borderBottomRightRadius: 14, borderTopWidth: 0, borderWidth: 1, flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 58, padding: 8 },
  mapRouteIdentity: { alignItems: 'center', flex: 2, flexBasis: 180, flexDirection: 'row', gap: 8, minWidth: 0 },
  mapRouteIcon: { alignItems: 'center', backgroundColor: portalPalette.accentSoft, borderRadius: 8, height: 32, justifyContent: 'center', width: 32 },
  mapRouteName: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 12, fontWeight: '900' },
  mapRoutePath: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 9 },
  mapStats: { alignItems: 'center', flex: 2, flexBasis: 190, flexDirection: 'row', gap: 18, justifyContent: 'center' },
  statValue: { color: portalPalette.text, fontFamily: Typography.display, fontSize: 14, fontWeight: '900', textAlign: 'center' },
  statLabel: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 8, marginTop: 2, textAlign: 'center' },
  mapActions: { flexDirection: 'row', gap: 7, marginLeft: 'auto' },
  assignedCard: { backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: 11, borderWidth: 1, gap: 6, overflow: 'hidden', padding: 7 },
  assignedHeader: { alignItems: 'center', flexDirection: 'row', gap: 7, justifyContent: 'space-between' },
  assignedName: { color: portalPalette.text, flex: 1, fontFamily: Typography.body, fontSize: 11, fontWeight: '900' },
  assignedDate: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 9 },
  assignedActions: { flexDirection: 'row', gap: 6, justifyContent: 'flex-end' },
  inlineFeedback: { alignItems: 'center', backgroundColor: portalPalette.infoSoft, borderColor: portalPalette.info, borderRadius: 9, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 34, paddingHorizontal: 10 },
  inlineFeedbackText: { color: portalPalette.text, flex: 1, fontFamily: Typography.body, fontSize: 11, fontWeight: '700' },
  editorTopActions: { flexDirection: 'row', gap: 7 },
  sortChip: { borderBottomColor: 'transparent', borderBottomWidth: 1, paddingHorizontal: 4, paddingVertical: 3, transitionDuration: '0.2s', transitionProperty: 'border-color, opacity', ':hover': { opacity: 0.8 }, ':active': { opacity: 0.7 } },
  sortChipActive: { borderBottomColor: portalPalette.accent },
  sortChipText: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 9, fontWeight: '800' },
  fullEditorShell: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 580, minWidth: 0 },
  editorTools: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: AppTheme.radius.sm, borderWidth: 1, flexBasis: 180, flexGrow: 1, gap: 6, maxWidth: 230, minWidth: 170, padding: 10 },
  editorMap: { flex: 6, flexBasis: 520, minHeight: 580, minWidth: 300 },
  editorDetails: { backgroundColor: portalPalette.surface, borderColor: portalPalette.line, borderRadius: AppTheme.radius.sm, borderWidth: 1, flexBasis: 300, flexGrow: 2, gap: 10, minWidth: 280, padding: 12 },
  toolButton: { alignItems: 'center', backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: AppTheme.radius.xs, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 36, paddingHorizontal: 9, transitionDuration: '0.2s', transitionProperty: 'background-color, border-color, transform', ':hover': { backgroundColor: 'rgba(255,255,255,0.075)' }, ':active': { transform: 'scale(0.97)' } },
  toolText: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 11, fontWeight: '800' },
  toolButtonActive: { backgroundColor: portalPalette.infoSoft, borderColor: portalPalette.info },
  editorLegend: { borderTopColor: portalPalette.line, borderTopWidth: 1, gap: 5, marginTop: 4, paddingTop: 10 },
  legendText: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 11, fontWeight: '700' },
  metricsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  metricText: { backgroundColor: portalPalette.surfaceSoft, borderRadius: AppTheme.radius.xs, color: portalPalette.text, fontFamily: Typography.mono, fontSize: 11, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 6 },
  pointList: { gap: 5, maxHeight: 250, overflow: 'auto' },
  pointRow: { backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: AppTheme.radius.xs, borderWidth: 1, minHeight: 40 },
  pointRowActive: { backgroundColor: portalPalette.infoSoft, borderColor: portalPalette.info },
  pointRowMain: { alignItems: 'center', flexDirection: 'row', gap: 8, minHeight: 40, paddingHorizontal: 8 },
  pointTitle: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 12, fontWeight: '900' },
  insertSegmentButton: { alignItems: 'center', borderTopColor: portalPalette.line, borderTopWidth: 1, flexDirection: 'row', gap: 4, justifyContent: 'center', minHeight: 24 },
  insertSegmentButtonActive: { backgroundColor: portalPalette.infoSoft },
  insertSegmentText: { color: portalPalette.info, fontFamily: Typography.body, fontSize: 10, fontWeight: '800' },
  editorFooter: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end', marginTop: 'auto' },
  secondaryButton: { alignItems: 'center', borderColor: portalPalette.lineStrong, borderRadius: AppTheme.radius.sm, borderWidth: 1, justifyContent: 'center', minHeight: 36, paddingHorizontal: 12, transitionDuration: '0.2s', transitionProperty: 'background-color, border-color, transform', ':hover': { backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.muted }, ':active': { transform: 'scale(0.97)' } },
  sectionEyebrow: { color: portalPalette.muted, fontFamily: Typography.body, fontSize: 11, fontWeight: '900', letterSpacing: 0.6, textTransform: 'uppercase' },
  previewPanel: { backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: AppTheme.radius.sm, borderWidth: 1, gap: 10, overflow: 'hidden', padding: 10 },
  catalogEditor: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  editorHeading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  editorTitle: { color: portalPalette.text, fontFamily: Typography.display, fontSize: 18, fontWeight: '900' },
  catalogToolbar: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  searchInput: { borderRadius: AppTheme.radius.sm, borderWidth: 1, flexBasis: 260, flexGrow: 1, fontFamily: Typography.body, fontSize: 13, minHeight: 40, paddingHorizontal: 12 },
  chipRow: { flexDirection: 'row', gap: 5 },
  filterChip: { backgroundColor: portalPalette.surfaceSoft, borderColor: portalPalette.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 5, transitionDuration: '0.2s', transitionProperty: 'background-color, border-color, transform', ':hover': { backgroundColor: 'rgba(255,255,255,0.075)' }, ':active': { transform: 'scale(0.96)' } },
  filterChipActive: { backgroundColor: portalPalette.infoSoft, borderColor: portalPalette.info },
  filterChipText: { color: portalPalette.text, fontFamily: Typography.body, fontSize: 10, fontWeight: '800' },
  catalogGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, minWidth: 0 },
  catalogCard: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexBasis: 230,
    flexDirection: 'column',
    flexGrow: 1,
    gap: 10,
    maxWidth: 360,
    padding: 12,
  },
  catalogCardContent: { alignItems: 'flex-start', flexDirection: 'row', gap: 8 },
  catalogCardActive: { backgroundColor: portalPalette.infoSoft, borderColor: portalPalette.accent },
  mapSelectToggle: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    minWidth: 0,
  },
  mapSelectButton: {
    alignItems: 'center',
    borderColor: portalPalette.lineStrong,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  mapSelectButtonActive: {
    backgroundColor: portalPalette.accent,
    borderColor: portalPalette.accent,
  },
  mapSelectText: {
    color: portalPalette.text,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  mapContainer: {
    gap: 8,
    minWidth: 0,
  },
  mapFallback: {
    alignItems: 'center',
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 220,
  },
  mapFallbackText: {
    color: portalPalette.muted,
    fontFamily: Typography.body,
    fontSize: 13,
  },
  mapHint: {
    color: portalPalette.info,
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  coordPreview: {
    backgroundColor: portalPalette.surfaceSoft,
    borderColor: portalPalette.line,
    borderRadius: AppTheme.radius.xs,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  coordText: {
    color: portalPalette.muted,
    fontFamily: Typography.mono,
    fontSize: 11,
  },
  continueButton: {
    alignItems: 'center',
    backgroundColor: '#EA1F23',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  formGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minWidth: 0,
  },
  input: {
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flex: 1,
    flexBasis: 220,
    fontFamily: Typography.body,
    fontSize: 13,
    minHeight: 40,
    minWidth: 0,
    paddingHorizontal: 12,
  },
  editorInput: {
    flexBasis: 40,
    flexGrow: 0,
    flexShrink: 0,
    height: 40,
  },
  segmentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    minWidth: 0,
  },
  segment: {
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexShrink: 1,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  segmentText: {
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  segmentDriver: {
    fontFamily: Typography.body,
    fontSize: 11,
    fontWeight: '700',
  },
  actions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'flex-end',
    minWidth: 0,
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 7,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 12,
    transitionDuration: '0.2s',
    transitionProperty: 'box-shadow, transform, opacity',
    ':active': { transform: 'scale(0.97)' },
  },
  primaryText: {
    color: '#FFFFFF',
    flexShrink: 1,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '900',
  },
  list: {
    gap: 10,
    minWidth: 0,
  },
  routeRow: {
    alignItems: 'flex-start',
    borderRadius: AppTheme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    minWidth: 0,
    padding: 12,
  },
  routeIcon: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.xs,
    flexShrink: 0,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  routeBody: {
    flex: 1,
    flexBasis: 260,
    minWidth: 0,
  },
  routeName: {
    fontFamily: Typography.body,
    fontSize: 14,
    fontWeight: '900',
    minWidth: 0,
  },
  routeMeta: {
    fontFamily: Typography.body,
    fontSize: 12,
    lineHeight: 18,
    minWidth: 0,
  },
  rowActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 8,
  },
  iconAction: {
    alignItems: 'center',
    borderRadius: AppTheme.radius.xs,
    flexShrink: 0,
    height: 34,
    justifyContent: 'center',
    transitionDuration: '0.2s',
    transitionProperty: 'background-color, transform',
    width: 34,
    ':active': { transform: 'scale(0.92)' },
  },
  continuityBanner: {
    alignItems: 'center',
    backgroundColor: portalPalette.info,
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    minWidth: 0,
    padding: 12,
    shadowColor: portalPalette.info,
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 4,
  },
  continuityText: {
    color: '#FFFFFF',
    flex: 1,
    flexBasis: 200,
    fontFamily: Typography.body,
    fontSize: 13,
    fontWeight: '800',
    minWidth: 0,
  },
  continuityButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: AppTheme.radius.sm,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  continuityButtonText: {
    color: '#FFFFFF',
    fontFamily: Typography.body,
    fontSize: 12,
    fontWeight: '900',
  },
  deleteRouteButton: {
    alignItems: 'center',
    backgroundColor: portalPalette.dangerSoft,
    borderRadius: 8,
    flexShrink: 0,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  disabledButton: {
    opacity: 0.55,
  },
});
