import { Platform, StyleSheet } from 'react-native';
import { AppTheme, DesignSystem, Typography } from '@/constants/theme';
import type { useAppTheme } from '@/src/hooks/use-app-theme';

export function createStyles(
  theme: ReturnType<typeof useAppTheme>['theme'],
  isCompact: boolean,
  isPhone: boolean
) {
  return StyleSheet.create({
    container: {
      flex: 1,
      minHeight: 0,
      gap: AppTheme.spacing.md,
      backgroundColor: theme.colors.background,
    },
    containerConversationOnly: {
      gap: 8,
      paddingBottom: 0,
    },
    header: {
      gap: 6,
      paddingTop: 4,
      minWidth: 0,
    },
    headerTitleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 16,
    },
    title: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 26 : 32,
      lineHeight: isPhone ? 31 : 38,
    },
    headerActionButton: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 8px 16px rgba(229, 30, 45, 0.2)',
          }
        : {
            shadowColor: theme.colors.accent,
            shadowOpacity: 0.2,
            shadowRadius: 8,
            shadowOffset: { width: 0, height: 4 },
            elevation: 4,
          }),
    },
    headerPills: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      gap: 8,
      paddingRight: 4,
    },
    categoryTabs: {
      flexDirection: 'row',
      gap: 8,
      paddingRight: 4,
    },
    categoryTabsScroll: {
      flexGrow: 0,
      flexShrink: 0,
      maxHeight: 40,
    },
    categoryTab: {
      minHeight: 38,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 13,
      paddingVertical: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    categoryTabActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    categoryTabText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '900',
    },
    categoryTabTextActive: {
      color: '#FFFFFF',
    },
    categoryTabCount: {
      minWidth: 22,
      height: 22,
      borderRadius: 999,
      paddingHorizontal: 7,
      backgroundColor: theme.mode === 'light' ? '#E8ECF3' : 'rgba(159, 176, 202, 0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    categoryTabCountActive: {
      backgroundColor: 'rgba(255,255,255,0.22)',
    },
    categoryTabCountText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '900',
    },
    categoryTabCountTextActive: {
      color: '#FFFFFF',
    },
    layout: {
      flex: 1,
      minHeight: 0,
      flexDirection: isCompact ? 'column' : 'row',
      gap: AppTheme.spacing.md,
      alignItems: 'stretch',
    },
    directoryPanel: {
      flex: isCompact ? 1 : undefined,
      width: isCompact ? '100%' : 368,
      minWidth: 0,
      minHeight: 0,
      borderRadius: isPhone ? 0 : 18,
      borderWidth: isPhone ? 0 : 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: isPhone ? 0 : 12,
      gap: 12,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 18px 36px rgba(4, 16, 27, 0.12)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.08,
            shadowRadius: 16,
            shadowOffset: { width: 0, height: 8 },
            elevation: 4,
          }),
    },
    conversationPanel: {
      flex: 1,
      minWidth: 0,
      minHeight: 0,
      borderRadius: isPhone ? 20 : 24,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      padding: isPhone ? 14 : 16,
      gap: 8,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 18px 36px rgba(4, 16, 27, 0.12)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.08,
            shadowRadius: 16,
            shadowOffset: { width: 0, height: 8 },
            elevation: 4,
          }),
    },
    conversationPanelMobile: {
      borderWidth: 0,
      borderRadius: 0,
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 0,
      gap: 0,
      backgroundColor: theme.mode === 'light' ? '#F7F4EE' : '#0B1118',
      shadowOpacity: 0,
      elevation: 0,
    },
    modeRow: {
      flexDirection: 'row',
      gap: 8,
      paddingRight: 4,
    },
    modeRowScroll: {
      flexGrow: 0,
      flexShrink: 0,
      maxHeight: 36,
    },
    modeChip: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 10,
      paddingVertical: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modeChipActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    modeChipCopy: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    modeChipText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
    },
    modeChipTextActive: {
      color: '#FFFFFF',
    },
    modeChipCount: {
      minWidth: 22,
      height: 22,
      paddingHorizontal: 7,
      borderRadius: 999,
      backgroundColor: theme.mode === 'light' ? '#E8ECF3' : 'rgba(159, 176, 202, 0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    modeChipCountActive: {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
    modeChipCountText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '800',
    },
    modeChipCountTextActive: {
      color: '#FFFFFF',
    },
    filterSummaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: -2,
    },
    filterSummaryText: {
      flex: 1,
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      lineHeight: 16,
    },
    directoryScroll: {
      flex: 1,
      minHeight: 0,
    },
    directoryContent: {
      gap: 8,
      paddingBottom: 4,
    },
    sectionBlock: {
      gap: 8,
    },
    sectionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 16,
      lineHeight: 22,
    },
    sectionHint: {
      flexShrink: 1,
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      lineHeight: 16,
      textAlign: 'right',
    },
    quickActionCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 9,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    quickActionCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    quickActionTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '800',
    },
    quickActionBody: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
    },
    conversationTile: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.mode === 'light' ? '#E5EAF1' : 'rgba(159, 176, 202, 0.14)',
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    conversationTileActive: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.surfaceAlt,
    },
    tileTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    tileLead: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: 0,
    },
    tileCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    tileTitle: {
      flex: 1,
      minWidth: 0,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '900',
    },
    tileTime: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '700',
    },
    tileMeta: {
      flex: 1,
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
    },
    tilePreviewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    tilePreview: {
      flex: 1,
      minWidth: 0,
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 13,
      lineHeight: 18,
    },
    groupAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tileStatusDot: {
      width: 9,
      height: 9,
      borderRadius: 999,
      backgroundColor: theme.colors.success,
    },
    tileStatusDotMuted: {
      backgroundColor: theme.colors.muted,
    },
    tileStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    tileStatusText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
    },
    unreadBubble: {
      minWidth: 22,
      height: 22,
      paddingHorizontal: 7,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    unreadBubbleText: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '800',
    },
    contactRow: {
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 2,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    contactActionButton: {
      width: 36,
      height: 36,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyStateCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    emptyStateCopy: {
      flex: 1,
      gap: 4,
    },
    emptyStateTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '800',
    },
    emptyStateBody: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 18,
    },
    backButton: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    backButtonText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '800',
    },
    headerBackButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: -6,
    },
    conversationHeader: {
      gap: 4,
      paddingHorizontal: isPhone ? 8 : 0,
      paddingTop: isPhone ? 2 : 0,
      paddingBottom: isPhone ? 7 : 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
    },
    conversationHeaderTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: isPhone ? 6 : 10,
    },
    conversationHeaderMain: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    groupAvatarLarge: {
      width: isPhone ? 40 : 48,
      height: isPhone ? 40 : 48,
      borderRadius: isPhone ? 20 : 18,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    conversationCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    conversationTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: isPhone ? 17 : 22,
      lineHeight: isPhone ? 21 : 28,
    },
    conversationSubtitle: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: isPhone ? 12 : 13,
      lineHeight: isPhone ? 15 : 18,
      maxWidth: 780,
    },
    conversationHeaderActions: {
      flexDirection: 'row',
      gap: isPhone ? 5 : 8,
      alignSelf: 'center',
    },
    conversationActionButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    conversationActionButtonActive: {
      borderColor: theme.colors.info,
      backgroundColor: theme.colors.infoSoft,
    },
    conversationActionButtonAudio: {
      backgroundColor: theme.colors.accentSoft,
      borderColor: theme.colors.accentSoft,
    },
    conversationActionButtonAudioActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    conversationActionButtonVideo: {
      backgroundColor: theme.colors.infoSoft,
      borderColor: theme.colors.infoSoft,
    },
    conversationActionButtonVideoActive: {
      backgroundColor: theme.colors.info,
      borderColor: theme.colors.info,
    },
    conversationActionButtonPressed: {
      opacity: 0.72,
      transform: [{ scale: 0.94 }],
    },
    conversationActionButtonDisabled: {
      opacity: 0.45,
    },
    callHub: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      padding: isPhone ? 14 : 16,
      gap: 12,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: `0px 16px 30px ${theme.colors.shadow}`,
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.18,
            shadowRadius: 20,
            shadowOffset: { width: 0, height: 10 },
            elevation: 6,
          }),
    },
    callHubHeader: {
      flexDirection: isPhone ? 'column' : 'row',
      justifyContent: 'space-between',
      alignItems: isPhone ? 'flex-start' : 'center',
      gap: 12,
    },
    callHubCopy: {
      flex: 1,
      gap: 4,
    },
    callHubTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
    },
    callHubSubtitle: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 13,
      lineHeight: 20,
    },
    callStarterGrid: {
      flexDirection: isPhone ? 'column' : 'row',
      gap: 12,
    },
    callStarterCard: {
      flex: 1,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      backgroundColor: theme.colors.accent,
      padding: 16,
      gap: 10,
    },
    callStarterCardVideo: {
      backgroundColor: theme.colors.info,
      borderColor: theme.colors.info,
    },
    callStarterCardDisabled: {
      opacity: 0.45,
    },
    callStarterTitle: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '800',
    },
    callStarterBody: {
      color: 'rgba(255,255,255,0.82)',
      fontFamily: Typography.body,
      fontSize: 13,
      lineHeight: 20,
    },
    callStage: {
      flexDirection: isPhone ? 'column' : 'row',
      gap: 10,
    },
    callTile: {
      flex: 1,
      minHeight: isPhone ? 180 : 196,
      borderRadius: 20,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: '#0A0F17',
      justifyContent: 'flex-end',
    },
    callTileSelf: {
      backgroundColor: '#131B26',
    },
    callTileVideo: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#000000',
    },
    callTileHiddenMedia: {
      position: 'absolute',
      width: 1,
      height: 1,
      opacity: 0.01,
    },
    callTileFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(11, 16, 27, 0.88)',
    },
    callTileIconShell: {
      width: 72,
      height: 72,
      borderRadius: 24,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.12)',
    },
    callTileIconShellSelf: {
      backgroundColor: theme.colors.info,
    },
    callTileFooter: {
      padding: 16,
      gap: 2,
      backgroundColor: 'rgba(8, 12, 19, 0.62)',
    },
    callTileLabel: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '800',
    },
    callTileCaption: {
      color: 'rgba(255,255,255,0.72)',
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 18,
    },
    callControlRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    callControlButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 16,
      backgroundColor: theme.colors.accent,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    callControlButtonActive: {
      backgroundColor: theme.colors.warning,
      borderColor: theme.colors.warning,
    },
    callControlButtonSecondary: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 16,
      backgroundColor: theme.colors.info,
      borderWidth: 1,
      borderColor: theme.colors.info,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    callControlButtonSecondaryActive: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.line,
    },
    callControlButtonDanger: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 16,
      backgroundColor: theme.colors.danger,
      borderWidth: 1,
      borderColor: theme.colors.danger,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    callControlText: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 13,
      fontWeight: '800',
    },
    callMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    callHubNotice: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 18,
    },
    messagesScroll: {
      flex: 1,
      minHeight: 0,
      backgroundColor: theme.mode === 'light' ? '#F7F4EE' : '#0B1118',
    },
    messagesList: {
      flexGrow: 1,
      gap: 7,
      paddingHorizontal: isPhone ? 10 : 0,
      paddingTop: 8,
      paddingBottom: 10,
    },
    dateSeparator: {
      alignSelf: 'center',
      borderRadius: 999,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 12,
      paddingVertical: 5,
      marginVertical: 2,
    },
    dateSeparatorText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '700',
    },
    messageRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 8,
    },
    messageRowOwn: {
      justifyContent: 'flex-end',
    },
    messageRowSystem: {
      justifyContent: 'center',
    },
    messageBubble: {
      maxWidth: isPhone ? '88%' : '78%',
      minWidth: 0,
      borderRadius: 18,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 12,
      paddingVertical: 9,
      gap: 5,
    },
    messageBubbleOwn: {
      backgroundColor: theme.colors.accent,
      borderBottomRightRadius: 5,
    },
    messageBubbleOther: {
      borderBottomLeftRadius: 5,
    },
    systemMessageBubble: {
      alignSelf: 'center',
      maxWidth: isPhone ? '92%' : 420,
      borderWidth: 1,
      borderColor: theme.colors.warning,
      backgroundColor: theme.mode === 'light' ? '#FFF8E7' : 'rgba(245, 158, 11, 0.12)',
    },
    messageBubbleAudio: {
      minWidth: isPhone ? 220 : 260,
      maxWidth: isPhone ? '88%' : 320,
    },
    messageBubbleMedia: {
      paddingHorizontal: 7,
      paddingVertical: 7,
      width: isPhone ? '78%' : 280,
    },
    mediaContainer: {
      gap: 6,
    },
    mediaPreviewShell: {
      position: 'relative',
      overflow: 'hidden',
      borderRadius: 16,
      backgroundColor: theme.colors.surfaceAlt,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 12px 24px rgba(4, 16, 27, 0.18)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.16,
            shadowRadius: 12,
            shadowOffset: { width: 0, height: 6 },
            elevation: 4,
          }),
    },
    messageImage: {
      width: '100%',
      aspectRatio: 1,
      borderRadius: 16,
      maxHeight: isPhone ? 260 : 320,
    },
    messageVideo: {
      width: '100%',
      aspectRatio: 16 / 9,
      borderRadius: 16,
      maxHeight: isPhone ? 220 : 280,
    },
    mediaLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: 'rgba(0,0,0,0.34)',
    },
    mediaErrorBox: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 16,
      backgroundColor: theme.colors.surfaceAlt,
    },
    mediaStateText: {
      color: '#FFFFFF',
      fontFamily: Typography.body,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
    },
    videoUnavailableBox: {
      minHeight: 150,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      padding: 16,
      backgroundColor: theme.colors.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.colors.line,
    },
    videoUnavailableTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
    },
    videoUnavailableText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 17,
      textAlign: 'center',
    },
    mediaCaption: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      paddingHorizontal: 8,
      paddingBottom: 4,
    },
    fullscreenOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.92)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    fullscreenImage: {
      width: '100%',
      height: '100%',
    },
    closeFullscreen: {
      position: 'absolute',
      top: 40,
      right: 20,
      zIndex: 10,
    },
    downloadFullscreen: {
      position: 'absolute',
      top: 40,
      right: 60,
      zIndex: 10,
    },
    messageHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
      minWidth: 0,
    },
    messageSender: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '800',
      flexShrink: 1,
    },
    systemMessageSender: {
      color: theme.colors.warning,
      textTransform: 'uppercase',
      letterSpacing: 0,
    },
    messageSenderOwn: {
      color: '#FFFFFF',
    },
    messageMeta: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '700',
      flexShrink: 0,
    },
    messageText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      lineHeight: 20,
      flexShrink: 1,
    },
    messageTextOwn: {
      color: '#FFFFFF',
    },
    deliveryMeta: {
      alignSelf: 'flex-end',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      minHeight: 14,
      marginTop: -1,
    },
    deliveryMetaText: {
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '700',
    },
    voiceMessageCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      minWidth: 0,
    },
    voicePlayButton: {
      width: 36,
      height: 36,
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    voicePlayButtonOwn: {
      backgroundColor: '#FFFFFF',
    },
    voiceCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    voiceTitle: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
    },
    voiceTitleOwn: {
      color: '#FFFFFF',
    },
    voiceMeta: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '700',
    },
    voiceMetaOwn: {
      color: 'rgba(255,255,255,0.76)',
    },
    voiceMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    voiceStateText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 10,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    voiceProgressTrack: {
      height: 4,
      borderRadius: 999,
      backgroundColor: theme.colors.surface,
      overflow: 'hidden',
    },
    voiceProgressTrackOwn: {
      backgroundColor: 'rgba(255,255,255,0.24)',
    },
    voiceProgressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: theme.colors.accent,
    },
    voiceProgressFillOwn: {
      backgroundColor: '#FFFFFF',
    },
    voiceErrorInline: {
      color: theme.colors.warning,
      fontFamily: Typography.body,
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '700',
    },
    retryMessageButton: {
      alignSelf: 'flex-end',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      marginTop: 2,
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    retryMessageText: {
      color: theme.colors.danger,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '800',
    },
    retryMessageTextOwn: {
      color: '#FFFFFF',
    },
    composerShell: {
      flexShrink: 0,
      gap: 6,
      paddingHorizontal: isPhone ? 10 : 0,
      paddingTop: 8,
      paddingBottom: isPhone ? 8 : 0,
      borderTopWidth: 1,
      borderTopColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
    },
    composerBar: {
      minHeight: 48,
      flexShrink: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    composerInputShell: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      minHeight: 44,
      maxHeight: 92,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    composerInput: {
      minHeight: 28,
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      lineHeight: 20,
      textAlignVertical: 'top',
    },
    attachButton: {
      flexShrink: 0,
      width: 44,
      height: 44,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: theme.colors.line,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceAlt,
    },
    voiceButton: {
      flexShrink: 0,
      width: 44,
      height: 44,
      borderRadius: 17,
      backgroundColor: theme.colors.accent,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sendIconButton: {
      flexShrink: 0,
      width: 44,
      height: 44,
      borderRadius: 17,
      backgroundColor: theme.colors.accent,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    controlPressed: {
      opacity: DesignSystem.opacity.pressed,
      transform: [{ scale: 0.96 }],
    },
    voiceButtonRecording: {
      backgroundColor: theme.colors.danger,
      borderColor: theme.colors.danger,
    },
    voiceButtonLoading: {
      opacity: 0.88,
    },
    voiceButtonDisabled: {
      opacity: 0.45,
    },
    recorderHint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    recorderHintText: {
      flex: 1,
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 18,
    },
    sheetBackdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(7, 11, 19, 0.28)',
      paddingHorizontal: isPhone ? 12 : 24,
      paddingBottom: isPhone ? 10 : 24,
    },
    bottomSheet: {
      width: '100%',
      maxWidth: 560,
      maxHeight: '82%',
      alignSelf: 'center',
      borderRadius: 22,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 18,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 18px 38px rgba(4, 16, 27, 0.18)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.16,
            shadowRadius: 18,
            shadowOffset: { width: 0, height: 8 },
            elevation: 8,
          }),
    },
    sheetHandle: {
      width: 36,
      height: 4,
      borderRadius: 999,
      backgroundColor: theme.colors.line,
      alignSelf: 'center',
      marginBottom: 14,
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 12,
    },
    sheetHeaderCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    sheetTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
      lineHeight: 25,
    },
    sheetSubtitle: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 18,
    },
    sheetList: {
      maxHeight: 420,
    },
    sheetListContent: {
      gap: 8,
      paddingBottom: 4,
    },
    driverActionRow: {
      minHeight: 68,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surfaceAlt,
      paddingHorizontal: 10,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    driverActionCopy: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    driverActionName: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '900',
    },
    driverActionUnit: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      lineHeight: 16,
    },
    driverStatusPill: {
      flexShrink: 0,
      minHeight: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    driverStatusDot: {
      width: 8,
      height: 8,
      borderRadius: 999,
      backgroundColor: theme.colors.success,
    },
    driverStatusDotWarning: {
      backgroundColor: theme.colors.warning,
    },
    driverStatusDotDanger: {
      backgroundColor: theme.colors.danger,
    },
    driverStatusDotMuted: {
      backgroundColor: theme.colors.muted,
    },
    driverStatusText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 11,
      fontWeight: '800',
    },
    optionsSheet: {
      width: '100%',
      maxWidth: 420,
      alignSelf: 'center',
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.colors.line,
      backgroundColor: theme.colors.surface,
      paddingVertical: 8,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: '0px 18px 38px rgba(4, 16, 27, 0.18)',
          }
        : {
            shadowColor: theme.colors.shadow,
            shadowOpacity: 0.16,
            shadowRadius: 18,
            shadowOffset: { width: 0, height: 8 },
            elevation: 8,
          }),
    },
    optionRow: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.line,
    },
    optionRowText: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 18,
      paddingVertical: 32,
    },
    emptyTitle: {
      color: theme.colors.text,
      fontFamily: Typography.display,
      fontSize: 20,
      textAlign: 'center',
    },
    emptyText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 14,
      lineHeight: 22,
      textAlign: 'center',
      maxWidth: 320,
    },
    sheetMediaOptions: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.line,
    },
    sheetMediaButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: theme.colors.background,
    },
    sheetMediaLabel: {
      color: theme.colors.text,
      fontFamily: Typography.body,
      fontSize: 14,
      fontWeight: '600',
    },
    typingIndicator: {
      paddingHorizontal: isPhone ? 10 : 0,
      paddingBottom: 4,
    },
    typingIndicatorText: {
      color: theme.colors.muted,
      fontFamily: Typography.body,
      fontSize: 12,
      fontStyle: 'italic',
    },
  });
}
